/* Build Your AI local MVP.  Data stays in this browser unless it is exported. */
const KEY = 'ai102-v1'+(window.BUILD_AI_CONFIG?.learnerStorageKey?':'+window.BUILD_AI_CONFIG.learnerStorageKey:'');
const presetCatalog = [
  {id:'tutor', icon:'🌿', title:'Biology tutor', purpose:'Help secondary-school learners understand biology clearly.', languages:'English', behavior:'Explain simply, use everyday examples, answer in English, and ask one checking question.', samples:['Explain photosynthesis to a 14-year-old.','Explain cell division in simple English.']},
  {id:'study', icon:'📚', title:'Study assistant', purpose:'Help students revise, practise, and build confidence.', languages:'English', behavior:'Break work into short steps, give a worked example, then a small practice question.', samples:['Help me revise algebra for a test.','Make me a simple study plan.']},
  {id:'business', icon:'📈', title:'Business helper', purpose:'Help a small business plan, communicate, and make decisions.', languages:'English', behavior:'Be practical, concise, and ask for missing business details before guessing.', samples:['Help me price a new service.','Write a polite message to a customer.']},
  {id:'aviation', icon:'✈️', title:'Aviation compliance assistant', purpose:'Help aviation teams find and understand approved internal procedures.', languages:'English', behavior:'Use supplied sources, distinguish facts from suggestions, state uncertainty, and never replace an approved manual or regulator.', samples:['What should I check before an internal audit?','Summarise this compliance finding.']},
  {id:'writer', icon:'✍️', title:'Writing assistant', purpose:'Help people plan, improve, and adapt clear writing.', languages:'English', behavior:'Preserve the author’s meaning, offer clear alternatives, and explain important edits briefly.', samples:['Improve this email without changing my meaning.','Help me write a respectful message.']},
  {id:'coach', icon:'🎯', title:'Personal coach', purpose:'Help someone define realistic goals and take a next step.', languages:'English', behavior:'Be encouraging but direct, suggest small practical actions, and avoid medical or professional claims.', samples:['Help me break a large goal into steps.','I keep putting off work; where should I start?']}
];
// The chooser offers three templates. Keep older definitions for saved projects.
const presets = presetCatalog.filter(preset=>['tutor','business','coach'].includes(preset.id));
const labs = [
  ['intro','Mission Briefing'],['lab1','Mission 1 · Meet AI'],['lab2','Mission 2 · Inside AI’s Words'],['lab3','Mission 3 · Show Your Agent How'],['lab4','Mission 4 · Shape Its Behaviour'],['lab5','Mission 5 · Assemble Your Agent'],['lab6','Mission 6 · Give It Tools'],['lab7','Mission 7 · Agent Launch Challenge'],['dashboard','My agents']
];
let store = load();
function defaultProject(){return {id:crypto.randomUUID(),name:'',purpose:'',preset:'',languages:'English',samples:[],examples:[],evaluation:[],knowledge:[],behavior:'Explain clearly and honestly.',temperature:.35,tools:{calculator:true,knowledge:false,notes:false,tasks:false},notes:[],tasks:[],model:null,createdAt:new Date().toISOString(),completed:[],guidance:{style:'auto',detail:'short',dailyMode:true,startedAt:null,voiceReplies:true,helpDay:null,understoodDays:[],interests:{},day1Step:1,day1LessonVersion:2},teacherMessages:[]};}
function normaliseProject(p){p.languages='English';if(p.model?.configuration)p.model.configuration.languages='English';p.guidance??={style:'auto',detail:'short',dailyMode:true,startedAt:null,voiceReplies:true,helpDay:null,understoodDays:[],interests:{}};p.guidance.style='auto';if(p.guidance.day1LessonVersion!==2){p.guidance.day1LessonVersion=2;p.guidance.day1Step=1;p.guidance.humanGuess='';p.guidance.day1AIChoice='';p.guidance.lessonMoment=null;}p.guidance.day1Step??=1;p.guidance.voiceReplies??=true;p.guidance.understoodDays??=[];p.guidance.interests??={};p.guidance.eveHistory??=[];p.guidance.learnerName??='';p.guidance.awaitingName??=false;p.guidance.eveWelcomes??={};p.teacherMessages??=[];p.tools??={calculator:true,knowledge:false,notes:false,tasks:false};return p;}
function load(){try {let x=JSON.parse(localStorage.getItem(KEY));if(x&&x.projects){x.projects.forEach(normaliseProject);return x;}return {projects:[],active:null,page:'intro'};}catch{return {projects:[],active:null,page:'intro'};}}
function save(){localStorage.setItem(KEY,JSON.stringify(store));}
function active(){let p=store.projects.find(p=>p.id===store.active);return p&&normaliseProject(p);}
function project(){let p=active(); if(!p){p=defaultProject();store.projects.push(p);store.active=p.id;save();}return p;}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
let eveDebug={status:'Waiting for Eve to begin.',heard:'No voice recording yet.',reply:'No OpenAI reply yet.',error:''};
function eveDebugMarkup(){if(!window.BUILD_AI_CONFIG?.debug)return '';return `<details class="card eve-debug" id="eve-debug"><summary><b>Eve diagnostic (temporary)</b></summary><p class="fineprint"><b>Voice step:</b> ${esc(eveDebug.status)}</p><p class="fineprint"><b>Eve heard:</b> ${esc(eveDebug.heard)}</p><p class="fineprint"><b>OpenAI replied:</b> ${esc(eveDebug.reply)}</p>${eveDebug.error?`<p class="warning"><b>Error:</b> ${esc(eveDebug.error)}</p>`:''}</details>`;}
function updateEveDebug(status,changes={}){Object.assign(eveDebug,{status,...changes});if(window.BUILD_AI_CONFIG?.debug)console.info('[Eve diagnostic]',eveDebug);let panel=document.querySelector('#eve-debug');if(panel)panel.outerHTML=eveDebugMarkup();}
function toast(msg){document.querySelector('.toast')?.remove();let e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.append(e);setTimeout(()=>e.remove(),2600);}
function complete(id){let p=project();if(!p.completed.includes(id))p.completed.push(id);if(id===store.page&&/^lab[1-7]$/.test(id)){p.guidance.practiceFinished??={};p.guidance.practiceFinished[id]=true;}save();}
function labDay(page){let n=Number((page||'').replace('lab',''));return Number.isInteger(n)&&n>=1&&n<=7?n:null;}
function availableDay(){return 7;}
function canOpen(page){let day=labDay(page),p=active();return !day||day<=availableDay(p);}
function go(page){if(!canOpen(page)){toast(`Mission ${labDay(page)} opens tomorrow. Today, focus on one small step.`);return;}unlockEveAudio();eveReplyRequest++;stopEve();store.page=page;save();render();window.scrollTo({top:0,behavior:'smooth'});}
function baseName(p){return p.name||'Your AI';}
function countTools(p){return Object.values(p.tools).filter(Boolean).length;}
function panel(){let p=active();if(!p||!p.guidance.learnerName||!p.completed.includes('intro'))return '';return `<aside class="ai-panel"><h2>MY AGENT</h2><div class="status"><i class="dot"></i>${p.model?'Agent setup ready':'Building'}</div><div class="mini"><div><span>Name</span><b>${esc(p.name||'Not chosen')}</b></div><div><span>Purpose</span><b>${esc(p.purpose?short(p.purpose,25):'Not chosen')}</b></div><div><span>Languages</span><b>${esc(p.languages)}</b></div><div><span>Examples</span><b>${p.examples.length}</b></div><div><span>Configuration</span><b>${esc(p.model?.name||'Not saved')}</b></div><div><span>Knowledge</span><b>${p.knowledge.length} sources</b></div><div><span>Tools</span><b>${countTools(p)}</b></div></div><div class="panel-actions"><button class="button ghost" onclick="exportProject()">Export this agent</button><button class="button secondary" onclick="go('dashboard')">All my agents</button></div></aside>`;}
function short(s,n){return s.length>n?s.slice(0,n-1)+'…':s;}
function nav(){return `<aside class="sidebar"><div class="brand">AI 102</div><div class="tagline">Build your own AI at your own pace.</div><nav class="lab-nav">${labs.map(([id,label])=>{let locked=!canOpen(id);return `<button class="nav-item ${store.page===id?'active':''} ${locked?'locked':''}" onclick="go('${id}')"><i class="nav-num">${id==='intro'?'◎':id==='dashboard'?'◫':id==='teacher'?'?':locked?'🔒':labDay(id)||label[0]}</i><span>${label}</span></button>`}).join('')}</nav><div class="side-foot">All seven lessons are open. Eve is here when you need her.</div></aside>`;}
function layout(content){document.querySelector('#app').innerHTML=`<div class="shell">${nav()}<main><div class="topbar"><b>AI 102</b></div>${content}${eveDebugMarkup()}</main>${panel()}</div>`;}
function evePortrait(){return `<img class="eve-portrait" src="assets/eve-teacher.png" alt="Eve, your African AI teacher" />`;}
function header(kicker,title,lead){let day=labDay(store.page);return `<header class="classroom-hero"><div><div class="eyebrow">${kicker}</div><h1 class="title">${title}</h1><p class="lead">${lead}</p></div><div class="teacher-illustration">${evePortrait()}<span class="teacher-caption">Eve · Your learning companion</span></div></header>${day?labCoach(day):''}`;}
function render(){let p=project();if(!p.guidance.learnerName&&store.page!=='intro')store.page='intro';let pages={intro,lab1,lab2,lab3,lab4,lab5,lab6,lab7,dashboard};layout((pages[store.page]||intro)());setTimeout(()=>{tokenize();temperaturePreview();},0);queueEveWelcome();}

function intro(){let p=project();if(!p.guidance.learnerName)return `<section class="course-welcome"><div class="welcome-copy"><div class="eyebrow">AI 102 · YOUR AI JOURNEY</div><h1>Understand AI. Build your own agent.</h1><p>Explore how AI works, practise each idea, and build an agent you can explain and test. Type your name to meet Eve.</p><form onsubmit="event.preventDefault();submitLearnerName()" novalidate><div class="field"><label for="learner-name">Your name</label><input id="learner-name" autocomplete="given-name" maxlength="80" required aria-describedby="learner-name-error" value="${esc(p.guidance.drafts?.intro?.['learner-name']||'')}" placeholder="For example: Emma" /></div><p id="learner-name-error" role="alert"></p><button class="button" type="submit">Start AI 102</button></form></div>${evePortrait()}</section>`;return `${header('MISSION BRIEFING','First, decide what your AI agent will help with.','Before Mission 1, choose your agent’s job, working name. All agents use English. Eve will guide you through building and testing it.')}${eveVoiceButton(0)}
<div class="card"><h2>What would you like your agent to help with?</h2><p class="muted">Pick a starting idea—we’ll learn and build it together.</p><div class="grid3">${presets.map(x=>`<button class="choice ${p.preset===x.id?'selected':''}" onclick="choosePreset('${x.id}')"><span class="preset-symbol" aria-hidden="true">${({tutor:'🔬',business:'📊',coach:'🧭'})[x.id]}</span><strong>${x.title}</strong><small>${esc(x.purpose)}</small></button>`).join('')}</div></div>
`;}
async function choosePreset(id){unlockEveAudio();let x=presets.find(a=>a.id===id);if(!x)return;let p=project();p.preset=x.id;p.name=p.name||x.title.split(' ').map(w=>w[0].toUpperCase()+w.slice(1)).join('');p.purpose=x.purpose;p.languages=x.languages;p.behavior=x.behavior;p.samples=x.samples;save();render();openAgentName();await eveTeachMoment(0,`The learner chose the ${x.title} starting idea. Explain in one simple sentence what that AI could help with. Then guide one next choice only: the preset job is fixed. Invite the learner to type an agent name in the open naming pop-up. Do not ask them to edit its purpose.`);}
function setTeachingStyle(style){project().guidance.style=style;save();toast('Eve will guide you in that way.');}
function setDetail(detail){project().guidance.detail=detail;save();toast(detail==='short'?'Short explanations selected.':'A little more help selected.');}
function saveBlueprint(){let p=project(),preset=presetCatalog.find(x=>x.id===p.preset);if(!preset){toast('Choose one starting idea first.');return;}const input=document.getElementById('agent-name');const name=(input?input.value:p.name||'').trim();if(!name){document.getElementById('agent-name-error').textContent='Please give your agent a name.';input.focus();return;}p.name=name.slice(0,80);p.purpose=preset.purpose;p.languages='English';if(p.guidance.drafts?.intro)delete p.guidance.drafts.intro['agent-name'];document.getElementById('agent-name-dialog')?.close();p.guidance.startedAt??=new Date().toISOString();complete('intro');save();go('lab1');}

function openAgentName(){const p=project();if(!p.preset)return;document.getElementById('agent-name-dialog')?.remove();const d=document.createElement('dialog');d.id='agent-name-dialog';d.className='agent-name-dialog';d.setAttribute('aria-labelledby','agent-name-title');d.innerHTML=`<form onsubmit="event.preventDefault();saveBlueprint()" novalidate><div class="eyebrow">${esc(day1Preset(p).title)}</div><h2 id="agent-name-title">Give your agent a name</h2><p class="muted">Its job is already chosen. Pick a name you like.</p><label for="agent-name">Agent name</label><input id="agent-name" maxlength="80" value="${esc(p.guidance.drafts?.intro?.['agent-name']??p.name)}" aria-describedby="agent-name-error" autocomplete="off" /><p id="agent-name-error" role="alert"></p><div class="actions"><button class="button" type="submit">Save name & begin Mission 1 →</button><button class="button secondary" type="button" onclick="document.getElementById('agent-name-dialog').close()">Back to choices</button></div></form>`;document.querySelector('main').append(d);d.showModal();d.querySelector('input').focus();d.querySelector('input').select();}
function day1Preset(p){return presetCatalog.find(x=>x.id===p.preset)||presets[0];}
function day1Question(p){return day1Preset(p).samples[0];}
function lab1(){
  let p=project(),preset=day1Preset(p),question=day1Question(p),step=p.guidance.day1Step,choice=p.guidance.day1AIChoice||preset.behavior,body;
  if(step===1) body=`<div class="card"><div class="step-label">STEP 1 OF 4 · YOU GUESS FIRST</div><h2>How might your ${esc(preset.title)} begin?</h2><p>A learner asks your AI:</p><div class="big-sentence">“${esc(question)}”</div><p>Write one helpful first sentence. There is no wrong answer.</p><input id="human-guess" placeholder="It could begin…" value="${esc(p.guidance.humanGuess||'')}"><div class="actions"><button class="button" onclick="revealAIGuess()">Now let my AI try</button></div></div>`;
  else if(step===2) body=`<div class="card"><div class="step-label">STEP 2 OF 4 · YOUR PRESET GUIDES THE AI</div><h2>What job did you give ${esc(p.name||preset.title)}?</h2><div class="big-sentence">${esc(preset.purpose)}</div><p>AI uses the selected preset’s purpose, examples, and behaviour rules to make a helpful best response. It does not think like a person or know the learner perfectly.</p><div class="actions"><button class="button" onclick="oneToken()">See its instructions</button></div></div>`;
  else if(step===3) body=`<div class="card"><div class="step-label">STEP 3 OF 4 · PAUSE AND NOTICE</div><h2>Your preset gives AI direction</h2><div class="big-sentence">${esc(choice)}</div><p>This is the response style your ${esc(preset.title)} was given. AI combines that direction with the learner’s question to make its best response.</p><div class="actions"><button class="button" onclick="advanceDay1(4)">Next: Make the request clearer</button></div></div>`;
  else body=day1Practice(preset,question);
  return `${header('MISSION 1 · WHAT IS AI?','AI is a pattern-finding helper.','AI is software that learns patterns from examples. Your preset gives it a job; your question gives it clues. Its answer can still be wrong.')}${body}`;
}
function day1Practice(preset,question){return `<div class="card"><div class="step-label">STEP 4 OF 4 · PRACTISE WITH EVE</div><h2>Make your preset AI’s request clearer</h2><p>Start with the preset question below. Add one useful detail — for example <b>for a Form Two learner</b>, <b>in Swahili</b>, or <b>in two short sentences</b>.</p><div class="field"><label>Improve this preset question</label><input id="prediction-input" value="${esc(question)}"></div><div class="eve-example"><b>Exercise 1 · Add one useful detail</b><p>Your preset tells the AI its job. Your extra words tell it what this particular learner needs.</p><button class="button secondary" onclick="checkDay1Clue()">I added a detail</button><p id="day1-clue-result" class="fineprint"></p></div><div class="eve-example"><b>Exercise 2 · One tiny question</b><p>Why can the response improve after you add a detail?</p><div class="actions"><button class="button secondary" onclick="answerDay1Reflection(true)">Because the preset gives direction and my new words make this request clearer</button><button class="button ghost" onclick="answerDay1Reflection(false)">Because AI now knows everything</button></div><p id="day1-reflection-result" class="fineprint"></p></div><p><b>Remember:</b> A preset gives your AI a job and response style. Your words give it clues about the specific help needed. Tomorrow Eve will show you the small pieces of text AI works with. They are called tokens.</p><div class="actions"><button class="button" onclick="finishLab('lab1','lab2')">Finish Mission 1</button></div></div>`;}
function checkDay1Clue(){let value=document.querySelector('#prediction-input').value.trim(),base=day1Question(project()).trim(),result=document.querySelector('#day1-clue-result');if(value.toLowerCase()===base.toLowerCase()||value.length<base.length+6){result.textContent='Add one small detail first — for example “in Swahili” or “for a Form Two learner”.';return;}eveTeachMoment(1,'The learner added a detail. Compare the visible question with the preset question. Explain whether the detail helps; do not assume every edit improves it.');result.textContent='✓ Great noticing. Your preset gives AI its job, and your extra words make this particular request clearer.';}
function answerDay1Reflection(correct){eveTeachMoment(1,correct?'The learner correctly identified why clues help. Reinforce this briefly and remind them AI can still make mistakes.':'The learner thinks AI knows everything. Gently correct this with one example from their preset, then invite another try.');let result=document.querySelector('#day1-reflection-result');result.textContent=correct?'✓ Exactly. The preset gives AI direction, while your new words give it better clues about this learner’s request.':'Almost. AI does not know everything. It improves because the preset gives direction and your new words make the request clearer.';}
function revealAIGuess(){let p=project(),input=document.querySelector('#human-guess');p.guidance.humanGuess=input?.value.trim()||'';p.guidance.day1Step=2;save();render();eveTeachMoment(1,'The learner has suggested how their selected preset AI could begin. Briefly thank them, then explain that the selected preset gives the AI a job, examples, and response rules. Invite them to let their AI respond.');}
function advanceDay1(step){let p=project();p.guidance.day1Step=step;save();render();if(step===4)eveTeachMoment(1,'The learner has seen that the selected preset gives AI direction. Explain that adding one useful detail to the preset sample question helps the AI make a more fitting response. Invite one small action only.');}
function oneToken(){let p=project(),piece=day1Preset(p).behavior;p.guidance.day1AIChoice=piece;p.guidance.day1Step=3;p.guidance.lessonMoment={day:1,piece,question:null};save();render();eveTeachMoment(1,`The learner has seen their selected preset rule: “${piece}”. Explain in plain language that this gives the AI direction, but it still uses the learner’s question to make its best response. Ask one specific question about what extra detail could help.`);}

function lab2(){let p=project();return `${header('MISSION 2 · SMALL PIECES','What is a token?','A token is a small piece of writing that AI reads. It can be a whole word, part of a word, or a sign like “!” or “,”.')}
<div class="card"><h2>See the small pieces</h2><p><b>Example:</b> “Hello!” can become two pieces: <span class="token">Hello</span> <span class="token">!</span></p><div class="field"><label>Type anything</label><textarea id="token-text" oninput="tokenize()">${esc(p.samples[1]||'Habari, naomba unisaidie kujifunza biology.')}</textarea></div><div id="tokens"></div><p id="token-count" class="muted"></p></div>
<div class="card"><h2>Who will your AI speak with?</h2><div class="field"><label>Two typical questions users might ask</label><div class="split"><input id="sample1" value="${esc(p.samples[0]||'Explain photosynthesis simply.')}" /><input id="sample2" value="${esc(p.samples[1]||'Explain cell division in simple English.')}" /></div></div><div class="actions"><button class="button" onclick="saveLab2()">Save language and questions →</button></div></div>`;}
function tokenize(){let e=document.querySelector('#token-text');if(!e)return;let parts=e.value.match(/[\p{L}\p{N}]+|[^\s\p{L}\p{N}]/gu)||[];document.querySelector('#tokens').innerHTML=`<div>${parts.map((x,i)=>`<span class="token" title="Example text piece">${esc(x)}</span>`).join('')}</div>`;document.querySelector('#token-count').textContent=`${parts.length} illustrated pieces. Real model token boundaries can be different.`}
function saveLab2(){let p=project();p.samples=[document.querySelector('#sample1').value.trim(),document.querySelector('#sample2').value.trim()].filter(Boolean);complete('lab2');save();go('lab3');}

function lab3(){let p=project();return `${header('MISSION 3 · EXAMPLES AND INFORMATION','Show your agent what useful help looks like.','Answer examples guide its style. Reference information gives it facts to look up. You are configuring an agent, not changing the model.')}
<div class="grid"><div class="card"><h2>Add an answer example</h2><div class="field"><label>User question</label><textarea id="ex-in" placeholder="${esc(p.samples[0]||'Explain photosynthesis to a 14-year-old.')}"></textarea></div><div class="field"><label>Ideal answer</label><textarea id="ex-out" placeholder="Write a useful answer you want your agent to follow."></textarea></div><div class="actions"><button class="button" onclick="addExample()">Approve example</button><button class="button secondary" onclick="useSuggestedExample()">Use a suggested example</button></div></div><div class="card"><h2>Your approved examples <span class="pill">${p.examples.length}</span></h2><div id="example-list">${examplesHTML(p)}</div></div></div>
<div class="card"><h2>Knowledge library</h2><p class="muted">Paste a reliable note, procedure, or fact for your agent to look up when needed.</p><div class="field"><label>Source title</label><input id="source-title" placeholder="For example: Biology notes — photosynthesis" /></div><div class="field"><label>Source content</label><textarea id="source-content" placeholder="Paste useful information here…"></textarea></div><div class="actions"><button class="button secondary" onclick="addKnowledge()">Add source</button><button class="button" onclick="finishLab('lab3','lab4')">Continue to behaviour →</button></div></div>`;}
function examplesHTML(p){return p.examples.length?p.examples.map((x,i)=>`<div class="list-card"><b>${esc(short(x.input,62))}</b><p>${esc(short(x.output,140))}</p><button class="button danger" onclick="removeExample(${i})">Remove</button></div>`).join(''):'<p class="empty">Complete three answer-example exercises for your agent.</p>';}
function addExample(){let a=document.querySelector('#ex-in').value.trim(),b=document.querySelector('#ex-out').value.trim();if(!a||!b){toast('Add both a question and an ideal answer.');return;}let p=project();p.examples.push({input:a,output:b,author:'Learner approved'});save();render();eveTeachMoment(3,"The learner approved an example. Refer to the current example count. Explain the next small task without claiming the answer is correct unless you have checked its content.");}
function useSuggestedExample(){let p=project(),q=p.samples[p.examples.length%Math.max(p.samples.length,1)]||'Explain this clearly.';document.querySelector('#ex-in').value=q;document.querySelector('#ex-out').value=`Here is a clear explanation. Start with the main idea, then use a simple example. If any part is confusing, tell me which part and I will explain it another way.`;}
function removeExample(i){project().examples.splice(i,1);save();render();}
function addKnowledge(){let title=document.querySelector('#source-title').value.trim(),content=document.querySelector('#source-content').value.trim();if(!title||!content){toast('Give the source a title and some content.');return;}project().knowledge.push({title,content});save();toast('Knowledge source saved.');render();}

function lab4(){let p=project();return `${header('LAB 4 · BEHAVIOUR','Why does AI behave differently?','Give your AI clear rules, such as “use simple words.” Try the creativity example and decide what suits its job.')}
<div class="grid"><div class="card"><h2>Focused or creative?</h2><p class="muted">Temperature controls how predictable the next token choices are.</p><div class="range-line"><b>Focused</b><input type="range" min="0" max="1.3" step=".1" value="${p.temperature}" id="temp" oninput="temperaturePreview()"><b>Creative</b></div><p>Temperature: <b id="temp-value">${p.temperature}</b></p><div id="temp-answer" class="answer"></div></div><div class="card"><h2>Write the behaviour rules</h2><div class="field"><label>How should ${esc(baseName(p))} answer?</label><textarea id="behavior">${esc(p.behavior)}</textarea></div><p class="fineprint">Good rules are observable: “keep the first answer under 150 words” is more useful than “be helpful.”</p></div></div>
<div class="card"><h2>Questions to test it with</h2><p class="muted">Use different questions from your examples. Check whether your AI helps with something it has not practised.</p><div class="split"><input id="eval1" value="${esc(p.evaluation[0]||p.samples[0]||'Explain a difficult concept simply.')}" /><input id="eval2" value="${esc(p.evaluation[1]||p.samples[1]||'Give a helpful answer in Swahili.')}" /></div><div class="actions"><button class="button" onclick="saveLab4()">Save behaviour and tests →</button></div></div>`;}
function temperaturePreview(){let control=document.querySelector('#temp'),value=document.querySelector('#temp-value'),answer=document.querySelector('#temp-answer');if(!control||!value||!answer)return;let v=Number(control.value),t=v<.35?'DNA is like an instruction manual stored inside every cell.':v<.8?'Think of DNA as a recipe book that tells cells how to build and run a living thing.':'Imagine every cell holding a tiny library of blueprints; DNA is the collection of pages that helps life keep its shape.';value.textContent=v.toFixed(1);answer.textContent=t;}
function saveLab4(){let p=project();p.temperature=Number(document.querySelector('#temp').value);p.behavior=document.querySelector('#behavior').value.trim()||p.behavior;p.evaluation=[document.querySelector('#eval1').value.trim(),document.querySelector('#eval2').value.trim()].filter(Boolean);complete('lab4');save();go('lab5');}

function lab5(){let p=project(),ready=p.examples.length>=3;return `${header('MISSION 5 · ASSEMBLE YOUR AGENT','Bring your agent together.','Today you connect the job, examples and instructions from earlier lessons. Assemble that setup and explore how its parts work together. Mission 6 adds tools; Mission 7 tests the complete agent.')}
<div class="card"><h2>Agent configuration</h2><p><b>Job:</b> ${esc(p.purpose)}</p><p><b>Instructions:</b> ${esc(p.behavior)}</p><p><b>Language:</b> ${esc(p.languages)} · <b>Suggested examples:</b> ${p.examples.length} · <b>Reference sources:</b> ${p.knowledge.length}</p><p>${ready?'Your suggested examples are ready. Saving keeps these parts together as one agent setup—it does not publish the agent. Next, explore how its job, instructions and example work together.':'Explore the three suggested examples in Mission 3 first.'}</p>${p.model?`<button class="button" onclick="go(\'lab6\')">Continue to tools →</button>`:`<button class="button" ${ready?'':'disabled'} onclick="createModel()">Assemble my agent →</button>`}</div>
${p.model?evaluationHTML(p):'<div class="card"><h2>What goes into your agent?</h2><p>Its job gives direction, instructions set boundaries, examples show useful answers, and reference information supplies facts. Mission 6 adds tools for actions.</p></div>'}`;}
// The legacy field/function names preserve existing browser projects. This saves
// an agent configuration only; it never calls a model-training service.
async function createModel(){let p=project();if(p.examples.length<3){toast('Explore the three suggested examples first.');return;}p.model={...p.model,name:baseName(p),version:p.model?.version||1,kind:'agent-configuration',base:'Existing AI model',createdAt:p.model?.createdAt||new Date().toISOString(),examples:p.examples.length,configuration:JSON.parse(JSON.stringify({purpose:p.purpose,behavior:p.behavior,languages:p.languages,temperature:p.temperature,examples:p.examples,knowledge:p.knowledge,tools:p.tools}))};p.guidance.activityIndex??={};p.guidance.activityIndex.lab5=1;complete('lab5');save();toast('Your agent setup is ready. Explore its parts, then add tools in Mission 6.');render();}
function evaluationHTML(p){const c=p.model.configuration||p,x=presetPractice[p.preset]||presetPractice.tutor,example=c.examples?.find(e=>e.input===x.question)||c.examples?.[0],seen=p.guidance.day5Parts||[];return `<div class="card"><div class="eyebrow">MISSION 5 · CONNECT THE PARTS</div><h2>See how your agent’s parts work together</h2><p>Someone asks your ${esc(day1Preset(p).title)}:</p><blockquote class="prediction-request">${esc(example?.input||x.question)}</blockquote><p>Select each part to see how it helps with this request.</p><div class="stack">${[['job','1. Its job',c.purpose,'The job tells the agent who it helps and what to focus on.'],['instructions','2. Its instructions',c.behavior,'Instructions guide how it responds. They do not guarantee the answer is correct.'],['example','3. Its example',example?.output||'No saved example is available. Return to Mission 3 to explore suggested examples.','This saved example illustrates a useful response. It is guidance, not a live reply to this request.']].map(([key,title,text,why])=>`<button class="choice ${seen.includes(key)?'selected':''}" onclick="inspectAgentPart('${key}')"><strong>${title}</strong><small>${seen.includes(key)?esc(text):'Select to explore'}</small></button>${seen.includes(key)?`<p class="token-clue">${why}</p>`:''}`).join('')}</div><p>The existing AI supplies its language capability. These parts guide its work. Mission 6 adds tools so it can perform actions; Mission 7 tests the complete agent.</p><button class="button" ${['job','instructions','example'].every(k=>seen.includes(k))?'':'disabled'} onclick="go('lab6')">Continue to tools →</button></div>`;}
function inspectAgentPart(key){if(!['job','instructions','example'].includes(key))return;const p=project();p.guidance.day5Parts??=[];if(!p.guidance.day5Parts.includes(key))p.guidance.day5Parts.push(key);save();render();eveTeachMoment(5,`The learner explored the ${key} part of their saved agent setup. Explain how it guides the displayed request. This is a walkthrough, not a live reply or an answer comparison. Invite one remaining part, or Continue to tools if all three are explored.`);}

function lab6(){let p=project();let tool=[['calculator','Calculator','Solves arithmetic, conversions and simple calculations.'],['knowledge','Knowledge search','Looks through your saved knowledge sources.'],['notes','Notes','Saves a short note for this AI project.'],['tasks','Tasks','Creates and checks off simple tasks.']];return `${header('LAB 6 · TOOLS','A model can talk. Can it act?','Your agent decides when to use a tool, shows the action taken, and then uses the result in its answer.')}
<div class="grid">${tool.map(([id,n,d])=>`<button class="choice ${p.tools[id]?'selected':''}" onclick="toggleTool('${id}')"><strong>${p.tools[id]?'✓':'○'} ${n}</strong><small>${d}</small></button>`).join('')}</div><div class="card"><h2>Tool trace preview</h2><div class="trace">USER → “What is 25 × 4?”<br>AGENT → tool call: calculator({ expression: "25 * 4" })<br>TOOL → 100<br>AGENT → “25 × 4 = 100.”</div><p class="fineprint">The agent only has access to tools you enable. It never pretends it used a tool when it did not.</p><div class="actions"><button class="button" onclick="finishLab('lab6','lab7')">Save my tools →</button></div></div>`;}
function toggleTool(id){let p=project();p.tools[id]=!p.tools[id];markLearningStep("lab6");save();render();eveTeachMoment(6,`The learner changed the ${id} tool. Explain its enabled state and next small action.`);}

function lab7(){let p=project();if(!p.model)return `${header('LAB 7 · LAUNCH','Save your agent configuration first.','Your agent needs a saved configuration before its final tests.')}<div class="card"><button class="button" onclick="go('lab5')">Go to agent configuration</button></div>`;return `${header('LAB 7 · LAUNCH','Meet ${esc(baseName(p))}.','Your agent is ready: saved configuration, instructions, knowledge, and selected tools — all visible and editable.')}
<div class="grid"><div class="card"><h2>Agent playground</h2><div class="chat" id="chat"><div class="bubble agent">Hello — I’m ${esc(baseName(p))}. ${esc(firstBehavior(p))}</div></div><div class="split" style="margin-top:12px"><input id="chat-input" placeholder="Ask your AI something…" onkeydown="if(event.key==='Enter')sendChat()" /><button class="button" onclick="sendChat()">Send</button></div></div><div class="card"><h2>Agent settings</h2><div class="mini"><div><span>Model</span><b>${esc(p.model.name)}</b></div><div><span>Knowledge</span><b>${p.knowledge.length} sources</b></div><div><span>Tools</span><b>${countTools(p)} enabled</b></div><div><span>Temperature</span><b>${p.temperature.toFixed(1)}</b></div></div><div class="field"><label>Agent instructions</label><textarea id="agent-behavior">${esc(p.behavior)}</textarea></div><div class="actions"><button class="button secondary" onclick="saveAgentRules()">Save instructions</button><button class="button" onclick="launch()">Launch my AI</button></div></div></div>
<div class="card"><h2>Try these test scenarios</h2><div class="grid3"><div><b>Normal answer</b><p>${esc(p.samples[0]||'Ask a typical user question.')}</p></div><div><b>Knowledge lookup</b><p>${p.knowledge.length?'Ask something that appears in your library.':'Add a source in Lab 3, then test it here.'}</p></div><div><b>Tool usage</b><p>Ask “What is 15% of 800?” to test the calculator.</p></div></div></div>`;}
function firstBehavior(p){return (p.behavior||'I will help clearly.').split(/[.!]/)[0]+'.';}
function saveAgentRules(){project().behavior=document.querySelector('#agent-behavior').value.trim();save();toast('Agent instructions saved.');}
function launch(){complete('lab7');save();toast(`${baseName(project())} is saved in this browser. It has not been published online.`);go('dashboard');}
const lessonNotes={
  1:{name:'What is AI?',simple:'AI is a computer helper that uses its chosen job, examples, and behaviour rules to make a helpful best response to a learner’s request.',example:'A biology tutor preset gets a biology question and is guided to explain simply. A business helper preset gets a business question and is guided to be practical.',try:'Use your preset’s sample question and add one useful detail about what the learner needs.'},
  2:{name:'Tokens',simple:'Before AI can work with a sentence, it breaks the sentence into small pieces called tokens.',example:'“I love biology!” may become small pieces like “I”, “ love”, “ biology”, and “!”.',try:'Paste one short sentence in the Token Lab. Do not worry about the numbers—just look at the coloured pieces.'},
  3:{name:'Examples',simple:'Explore three ready-made request-and-response examples for the chosen agent. Explain how they guide useful help, honest limits and focused answers. The learner does not write or approve examples.',example:'Each suggested example pairs a request with a response and explains the behaviour it illustrates.',try:'Reveal why the current suggested example is useful, then move to the next example. After all three, try the small understanding check.'},
  4:{name:'Temperature and instructions',simple:'Temperature controls variety in the AI’s choices, not heat, intelligence or guaranteed accuracy. Lower settings tend to be more consistent; higher settings allow more variety. Instructions guide how the agent helps.',example:'The page compares two prepared replies for the chosen agent; these are illustrations, not live model outputs.',try:'Compare both settings, read the preset instructions and try the temperature understanding check. Do not ask the learner to write rules or test questions.'},
  5:{name:'Agent configuration',simple:'Assemble the agent’s job, instructions, examples and reference information. Save its setup and explore how its parts guide one request. An existing AI supplies the language capability; you do not change that model.',example:'An agent is like a worker with a job description, instructions, reference folder and toolbox.',try:'Review your agent’s components, then explore the saved parts.'},
  6:{name:'Tools',simple:'A tool performs a specific action. Biology tutor searches the supplied course note, Business helper calculates profit and Personal coach saves a small task. Explain only the chosen agent’s tool and actual result.',example:'The page shows the request, why the recommended tool is needed, its local action, its result and prepared final wording.',try:'Enable the suggested tool, run the task and inspect the result. No unexplained tool selection. Never claim local actions send reminders, search the internet or produce live AI replies.'},
  7:{name:'Launch',simple:'Your AI agent brings together your model, instructions, knowledge, and tools in one place.',example:'A tutor can explain a topic, search your notes, then ask a checking question.',try:'Ask one normal question in the playground. You do not need to test everything today.'}
};
const startHereLesson={name:'Mission Briefing',simple:'Before Mission 1, the learner chooses who their AI will help and gives it a simple starting purpose, name. All agents use English.',try:'Choose one starting idea, then save the blueprint when the purpose and name feel right.'};
function labCoach(day){return eveVoiceButton(day);}
function eveVoiceButton(day){return `<button class="eve-orb" id="eve-orb" onclick="useEve(${day})" aria-label="Talk to Eve"><span>✦</span><small>Talk to Eve</small></button>`;}
function eveActivityKey(day){
 if(pendingCheck)return `day${day}-check`;
 if(day===2){const input=document.getElementById('day2-answer');return input?'day2-answer':`day2-step-${project().guidance.day2Step||1}`;}
 if(day===3)return `day3-example-${project().guidance.day3ExampleStep||0}`;
 if(day===7){const tests=project().guidance.launchTests||{},kind=['normal','difficult','tool'].find(name=>!tests[name])||'done';return `day7-${kind}`;}
 if(day!==1)return `day${day}-activity-${project().guidance.activityIndex?.[`lab${day}`]||0}`;
 const input=document.querySelector('textarea[id^="day1-answer-"]');
 return input?input.id:'day1-choice';
}
function evePayload(day,message,turnKind='conversation',transition=null){
 const p=project(),lesson=day===0?startHereLesson:(lessonNotes[day]||lessonNotes[1]),preset=day1Preset(p),key=eveActivityKey(day);
 p.guidance.eveGreeted??=(p.guidance.eveHistory||[]).some(turn=>turn.role==='eve');
 const turns=(p.guidance.eveHistory||[]).filter(turn=>turn.day===day&&turn.pageContextVersion===3&&turn.activityKey===key).slice(-8).map(turn=>({role:turn.role,text:turn.text.slice(0,2000)}));
 const input=day===1?document.querySelector('textarea[id^="day1-answer-"]'):day===2?document.getElementById('day2-answer'):null,q=day===1&&input?day1Questions[input.id.replace('day1-answer-','')]:day===2&&input?day2Question:null;
 const x=presetPractice[p.preset]||presetPractice.tutor;
 const context=input?.id==='day1-answer-predict'?x.question:input?.id==='day1-answer-evidence'?x.hard:'';
 return {has_greeted:p.guidance.eveGreeted,lesson:lesson.name,lesson_summary:day===1&&q?q.idea:day===2&&q?q.idea:lesson.simple,activity:teacherPageContext(day).slice(0,2000),learner_message:message.slice(0,2000),recent_turns:turnKind==='guidance'?[]:turns,learner_interest:Object.values(p.guidance.interests||{}).join(', ').slice(0,180),learner_name:p.guidance.learnerName,language:p.languages,preset_title:p.preset?preset.title:'',preset_purpose:p.preset?preset.purpose:'',preset_examples:day===1?[]:p.preset?preset.samples:[],available_presets:day===0?presets.map(x=>`${x.title}: ${x.purpose}`):[],turn_kind:turnKind,current_question:q?.question||'',question_context:context,answer_guidance:q?.rubric||'',previous_takeaway:transition?.previous||'',lesson_connection:transition?.connection||'',opening_action:transition?.opening||''};
}
function saveEveTurn(day,role,text){let p=project();p.guidance.eveHistory.push({day,role,text,at:Date.now(),pageContextVersion:3,activityKey:eveActivityKey(day)});p.guidance.eveHistory=p.guidance.eveHistory.slice(-40);save();}
async function sendLiveEve(day,message){let requestId=++eveReplyRequest;saveEveTurn(day,'learner',message);updateEveDebug('Sending what Eve heard to OpenAI…',{heard:message,error:''});try{let reply=await window.BuildAICloud.teacherReply(evePayload(day,message));if(requestId!==eveReplyRequest)return;saveEveTurn(day,'eve',reply.text);updateEveDebug('OpenAI replied. Making Eve’s voice…',{reply:reply.text});playLiveEve(reply.text,day);}catch(error){if(requestId!==eveReplyRequest)return;updateEveDebug('Eve could not get a reply.',{error:error.message});toast(error.message);}}
let eveRecordingState=null,eveAudio=null,eveAudioDay=null,eveAudioContext=null,eveAudioRequest=0,eveReplyRequest=0;
function unlockEveAudio(){let AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return null;eveAudioContext??=new AudioContext();if(eveAudioContext.state==='suspended')eveAudioContext.resume().catch(()=>{});return eveAudioContext;}
function setEveOrb(day,label,icon='✦'){let button=document.querySelector('#eve-orb');if(!button)return;button.onclick=()=>useEve(day);button.innerHTML=`<span>${icon}</span><small>${label}</small>`;button.setAttribute('aria-label',label);}
function stopEve(){eveAudioRequest++;if(eveAudio){eveAudio.onended=null;try{eveAudio.stop();}catch{}}eveAudio=null;let day=eveAudioDay||labDay(store.page)||0;eveAudioDay=null;setEveOrb(day,project().guidance.awaitingName?'Tell Eve your name':'Talk to Eve');}
async function playLiveEve(text,day){let requestId=++eveAudioRequest;updateEveDebug('Turning Eve’s reply into speech…',{reply:text});try{let audio=await window.BuildAICloud.teacherSpeech(text);if(requestId!==eveAudioRequest)return;let context=unlockEveAudio();if(!context)throw new Error('Audio is not available.');let bytes=Uint8Array.from(atob(audio.audio_base64),character=>character.charCodeAt(0)),buffer=await context.decodeAudioData(bytes.buffer);if(requestId!==eveAudioRequest)return;stopEve();let source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);eveAudio=source;eveAudioDay=day;setEveOrb(day,'Stop Eve','■');source.onended=()=>{if(eveAudio===source){stopEve();updateEveDebug('Eve finished speaking.');}};source.start();updateEveDebug('Eve is speaking.');}catch(error){if(requestId===eveAudioRequest){updateEveDebug('Eve could not make audio.',{error:error.message});toast('Eve could not speak just now. Check that her teacher service is running.');}}}
async function useEve(day){unlockEveAudio();if(eveAudio){stopEve();return;}await toggleEveRecording(day);}
function startAI102(){submitLearnerName();}
function nameFromSpeech(text){let name=text.replace(/^(my name is|i am|i'm|this is)\s+/i,'').replace(/[^\p{L}\s'-]/gu,'').trim().split(/\s+/).slice(0,3).join(' ');return name?name.replace(/\b\p{L}/gu,letter=>letter.toUpperCase()):'';}
let evePageVisit='',evePreviousPage='',eveWelcomeTimer=null,eveTeachingRevision=0;
function claimEveTeachingEvent(day){
 if(store.page!==(day===0?'intro':`lab${day}`))return;
 eveTeachingRevision++;evePageVisit=project().id+':'+store.page;
 clearTimeout(eveWelcomeTimer);eveWelcomeTimer=null;
}
function queueEveWelcome(){
 clearTimeout(eveWelcomeTimer);
 const page=store.page,id=project().id,revision=eveTeachingRevision;
 eveWelcomeTimer=setTimeout(()=>{
  eveWelcomeTimer=null;
  if(store.page===page&&project().id===id&&revision===eveTeachingRevision)void maybeWelcomeEve();
 },0);
}
async function maybeWelcomeEve(){
  const p=project(),page=store.page,day=page==='intro'?0:labDay(page);
  if(day===null||!p.guidance.learnerName)return;
  const visit=p.id+':'+page;
  if(evePageVisit===visit)return;
  evePageVisit=visit;
  const transition=courseTransition(evePreviousPage,page);evePreviousPage='';
  const pageInstruction=day===0?`This is Mission Briefing, before Mission 1. ${p.guidance.eveGreeted?'Continue directly without a greeting or introduction.':'Welcome the learner once by name.'} Help with the current setup action. Mention only the exact available presets.`:transition?`The learner has just moved from ${transition.from==='intro'?'Mission Briefing':`Mission ${labDay(transition.from)}`} to Mission ${day}. Continue without a greeting. Make one brief connection, then teach only the first action.`:`The learner opened Mission ${day}. Continue without a greeting. Teach only the current visible activity. Do not pretend they just completed another lesson and do not recap a different mission.`;
  await eveTeachMoment(day,`${pageInstruction} Use the private teaching context silently. If an answer has already been reviewed, acknowledge it briefly and invite the Continue button; otherwise wait for an answer to the current question. Do not restart completed activities.`,transition);
}
async function eveTeachMoment(day,instruction,transition=null){let requestId=++eveReplyRequest;stopEve();unlockEveAudio();updateEveDebug('Asking OpenAI for Eve’s next teaching step.',{error:''});try{let reply=await window.BuildAICloud.teacherReply(evePayload(day,instruction,'guidance',transition));if(requestId!==eveReplyRequest)return;saveEveTurn(day,'eve',reply.text);updateEveDebug('OpenAI sent Eve’s teaching reply.',{reply:reply.text});playLiveEve(reply.text,day);}catch(error){if(requestId!==eveReplyRequest)return;updateEveDebug('Eve could not get her teaching reply.',{error:error.message});toast('Eve could not guide this step. Please check that her teacher service is running.');}}
async function toggleEveRecording(day){if(eveRecordingState){eveRecordingState.recorder.stop();setEveOrb(day,'Eve is listening…','●');updateEveDebug('Transcribing your recording…');return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){updateEveDebug('This browser cannot record voice.',{error:'Voice recording is not available in this browser.'});toast('Voice recording is not available in this browser.');return;}try{let stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[],recorder=new MediaRecorder(stream);eveRecordingState={recorder,stream,day,chunks};recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onstop=async()=>{let active=eveRecordingState;eveRecordingState=null;active.stream.getTracks().forEach(track=>track.stop());try{let blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'}),language='en',heard=await window.BuildAICloud.teacherTranscribe(blob,language),profile=project().guidance;updateEveDebug('Eve heard your recording.',{heard:heard.text,error:''});if(profile.awaitingName){let name=nameFromSpeech(heard.text);if(!name){updateEveDebug('Eve could not recognise the name.',{error:'Try saying “My name is…” slowly.'});toast('Eve did not catch the name. Please try once more.');setEveOrb(day,'Tell Eve your name','🎙');return;}profile.learnerName=name;profile.awaitingName=false;store.page='intro';save();render();return;}await sendLiveEve(day,heard.text);}catch(error){updateEveDebug('Eve could not process the recording.',{error:error.message});toast(error.message);}setEveOrb(day,'Talk to Eve');};recorder.start();setEveOrb(day,'Stop and send','■');updateEveDebug('Eve is listening…',{error:''});}catch{updateEveDebug('Microphone access was not allowed.',{error:'Allow microphone access for this local page, then try again.'});toast('Microphone access was not allowed.');}}
function eveGuessMoment(moment){let detail=moment.question==='think'?`<p><b>Does AI think like a person?</b> No. AI does not have feelings, wants, or lived experience. It is very good at finding patterns and using them to make a helpful guess.</p>`:moment.question==='source'?`<p><b>Where did the guess come from?</b> Before you met it, AI practised on a lot of examples and learned patterns. Your sentence tells it which pattern might fit now. It is not reading the internet or someone’s mind when it guesses.</p>`:'';return `<div class="eve-moment"><b>Eve noticed something</b><p>AI guessed “${esc(moment.piece)}”. It did not know what you want. It used the words you gave it and patterns it learned to make a best guess.</p>${detail}<p><b>What would you like to understand?</b></p><div class="actions"><button class="button ghost" onclick="explainEveMoment('think')">Does AI think like me?</button><button class="button ghost" onclick="explainEveMoment('source')">Where did its guess come from?</button></div></div>`;}
function explainEveMoment(question){let p=project();if(!p.guidance.lessonMoment)return;p.guidance.lessonMoment.question=question;save();render();}
function speakEveIntro(day){if(!('speechSynthesis' in window)){toast('Voice is not available in this browser.');return;}let p=project(),lesson=lessonNotes[day],status=document.querySelector('#eve-voice-status'),intro=day===1?'Hi, my name is Eve. I will walk with you through this journey, one mission at a time. ':`Hi, I am Eve. This is Mission ${day}. `;let text=`${intro}Today we are learning about ${lesson.name}. ${lesson.simple} First, try the small activity below. Then come back and tell me if it made sense.`;window.speechSynthesis.cancel();let voice=new SpeechSynthesisUtterance(text);voice.lang='en-US';voice.rate=.88;voice.onstart=()=>{if(status)status.textContent='Eve is speaking…';};voice.onend=()=>{if(status)status.textContent='Eve has finished. Now try the small activity.';};voice.onerror=()=>{if(status)status.textContent='Voice could not play. Check your device volume and try again.';};window.speechSynthesis.speak(voice);}
function explainForInterest(lesson,interest){return `Think about ${interest}. ${lesson.example} We can use ${interest} as our familiar example while we learn this new idea.`;}
function understandLab(day){let p=project();if(!p.guidance.understoodDays.includes(day))p.guidance.understoodDays.push(day);p.guidance.helpDay=null;save();toast('Well done. Now try the small activity below.');render();}
function needHelpWithLab(day){let p=project();p.guidance.helpDay=day;save();render();}
function saveInterest(day){let input=document.querySelector(`#interest-${day}`),interest=input?.value.trim();if(!interest){toast('Tell Eve one thing you enjoy.');return;}let p=project();p.guidance.interests[day]=interest;p.guidance.helpDay=null;save();render();}
const videoScripts={
  1:'Habari! Today we begin with one big idea: what is AI? Your selected preset gives AI a job, example questions, and a response style. Open Mission 1, look at your preset’s sample question, and add one useful detail. That is all for today.',
  2:'Today, AI does not see a sentence exactly as we do. It breaks it into small pieces called tokens. Open Mission 2, type one sentence, and look at the coloured pieces. You do not need to understand the numbers.',
  3:'Today we teach AI with examples. Give it one question and the kind of answer you wish it would give. Think of it like showing a learner one good worked example. Make just one today.',
  4:'Today we choose how our AI behaves. Do you want it to use simple words, short answers, or everyday examples? Pick one rule. Small and clear is better than many rules.',
  5:'Today we assemble our agent. Review its job, instructions, examples and information, then save its configuration. Compare its answers to the same requests.',
  6:'Today we give our AI a tool. A tool is like giving a learner a calculator or a notebook. Start with one tool: calculator. Then ask it one calculation.',
  7:'Today we bring everything together: your model, its instructions, knowledge, and tools. Ask it one normal question. Congratulations—you have created an AI agent.'
};
function teachingAnswer(p,message){let day=labDay(store.page)||availableDay(p),lesson=lessonNotes[day]||lessonNotes[1],q=(message||'').toLowerCase(),style=p.guidance.style;let core=q.includes('what')||q.includes('explain')||q.includes('understand')?lesson.simple:lesson.try;if(q.includes('example')||style==='examples')core=`${lesson.simple}\n\nExample: ${lesson.example}`;if(style==='show')core=`${lesson.simple}\n\nLook for this in the lab: ${lesson.try}`;if(style==='steps')core=`1. Open today’s small activity.\n2. Do only the first action.\n3. ${lesson.try}`;if(style==='practice')core=`${lesson.simple}\n\nTiny try: ${lesson.try}`;if(p.guidance.detail==='normal')core+=`\n\nThe important word today is “${lesson.name}.” You do not need to memorise it—just notice it.`;return core;}
function teacher(){let p=project(),day=availableDay(p),lesson=lessonNotes[day]||lessonNotes[1],messages=p.teacherMessages.length?p.teacherMessages:[{role:'teacher',text:`Hi, my name is Eve. Today we will learn one small thing: ${lesson.name}. Tell me one word that feels confusing, and I will explain only that.`}];return `${header('EVE · YOUR AI TEACHER','Talk to me. I will go at your pace.','Speak or type. I will keep answers short and adapt to how you prefer to learn.')}
<div class="card"><h2>Ask about today’s small lesson</h2><div class="voice-card"><b>🎙 Voice Teacher</b><p>Say: “show me”, “go slowly”, “give an example”, or “let me try”. I will adapt how I teach.</p><div class="actions"><button class="button" onclick="startVoiceTeacher()">🎙 Talk to your teacher</button><button class="button ${p.guidance.voiceReplies?'secondary':''}" onclick="toggleVoiceReplies()">${p.guidance.voiceReplies?'🔊 Voice replies on':'🔇 Voice replies off'}</button></div><p id="voice-status" class="fineprint">Your voice is used only for this conversation and is not saved by this local app.</p></div><div class="chat" id="teacher-chat">${messages.map(m=>`<div class="bubble ${m.role==='learner'?'me':'agent'}">${esc(m.text)}</div>`).join('')}</div><div class="actions"><button class="button secondary" onclick="quickTeacher('Explain it in the easiest way')">Simplify it</button><button class="button secondary" onclick="quickTeacher('Show me an example')">Give an example</button><button class="button secondary" onclick="quickTeacher('Let me try')">Let me try</button><button class="button ghost" onclick="go('lab${day}')">Open today’s small activity</button></div><div class="split" style="margin-top:12px"><input id="teacher-input" placeholder="What is confusing?" onkeydown="if(event.key==='Enter')askTeacher()"><button class="button" onclick="askTeacher()">Ask</button></div></div>`;}
function learningStyleFromSpeech(message){let text=message.toLowerCase();if(/show|see|picture|visual|look/.test(text))return 'show';if(/slow|step|one by one|again|polepole/.test(text))return 'steps';if(/example|real life|mfano/.test(text))return 'examples';if(/try|practice|question|jaribu/.test(text))return 'practice';return null;}
function teacherReply(message){let p=project(),heardStyle=learningStyleFromSpeech(message);if(heardStyle&&heardStyle!==p.guidance.style)p.guidance.style=heardStyle;let reply=teachingAnswer(p,message);if(heardStyle){let names={show:'showing you',steps:'small steps',examples:'everyday examples',practice:'tiny practice questions'};reply=`I heard that you may learn best with ${names[heardStyle]}. I will use that style.\n\n${reply}`;}p.teacherMessages.push({role:'learner',text:message},{role:'teacher',text:reply});save();return reply;}
function askTeacher(){let input=document.querySelector('#teacher-input'),message=input.value.trim();if(!message)return;let reply=teacherReply(message);render();if(project().guidance.voiceReplies)speakTeacher(reply);}
function quickTeacher(message){document.querySelector('#teacher-input').value=message;askTeacher();}
function showAllScripts(){let p=project();p.teacherMessages.push({role:'teacher',text:Object.entries(videoScripts).map(([day,script])=>`MISSION ${day}: ${script}`).join('\n\n')});save();render();}
function toggleVoiceReplies(){let p=project();p.guidance.voiceReplies=!p.guidance.voiceReplies;save();render();}
function speakTeacher(text){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();let utterance=new SpeechSynthesisUtterance(text.replace(/\n/g,' '));let p=project();utterance.lang='en-US';utterance.rate=.92;window.speechSynthesis.speak(utterance);}
function startVoiceTeacher(){let Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){toast('Voice listening is not available in this browser. You can still type to your teacher.');return;}let p=project(),status=document.querySelector('#voice-status'),recognition=new Recognition();recognition.lang='en-US';recognition.interimResults=false;recognition.maxAlternatives=1;status.textContent='Listening… speak naturally.';recognition.onresult=(event)=>{let message=event.results[0][0].transcript;status.textContent=`I heard: “${message}”`;let reply=teacherReply(message);render();if(project().guidance.voiceReplies)speakTeacher(reply);};recognition.onerror=(event)=>{status.textContent=event.error==='not-allowed'?'Microphone permission was not allowed. You can type instead.':'I could not hear that. Please try again or type your question.';};recognition.start();}
async function sendChat(){let input=document.querySelector('#chat-input'),q=input.value.trim();if(!q)return;let p=project(),chat=document.querySelector('#chat');chat.insertAdjacentHTML('beforeend',`<div class="bubble me">${esc(q)}</div>`);input.value='';chat.scrollTop=chat.scrollHeight;if(window.BuildAICloud?.enabled()&&p.model?.adapterKey){try{let r=await window.BuildAICloud.chat(p,q);chat.insertAdjacentHTML('beforeend',`<div class="bubble agent">${esc(r.text)}</div>`);chat.scrollTop=chat.scrollHeight;return;}catch(error){chat.insertAdjacentHTML('beforeend',`<div class="bubble agent">The GPU service was unavailable, so I used local teaching mode. (${esc(error.message)})</div>`);}}let r=generateReply(q,p,'agent');chat.insertAdjacentHTML('beforeend',`${r.trace?`<div class="trace">${esc(r.trace)}</div>`:''}<div class="bubble agent">${esc(r.text)}</div>`);chat.scrollTop=chat.scrollHeight;}
function generateReply(q,p,mode){let lower=q.toLowerCase(), trace='';let known=p.knowledge.find(k=>k.content.toLowerCase().split(/\W+/).filter(w=>w.length>4).some(w=>lower.includes(w)));if(mode==='agent'&&p.tools.knowledge&&known){trace=`AGENT → knowledge_search(query: "${short(q,42)}")\nTOOL → found: ${known.title}`;return {trace,text:`According to “${known.title}”: ${short(known.content,500)}\n\n${close(p)}`};}
if(mode==='agent'&&p.tools.calculator&&(/\d/.test(q))){let normalized=q.replace(/[×x]/gi,'*').replace(/÷/g,'/'),expr=(normalized.match(/[\d.+*/()\-]+/g)||[]).join('').replace(/\s/g,'');if(expr&&/[+*/-]/.test(expr)){try{let value=Function('"use strict";return ('+expr+')')();trace=`AGENT → calculator(expression: "${expr}")\nTOOL → ${value}`;return {trace,text:`The result is ${value}. ${close(p)}`};}catch{}}let pct=q.match(/(\d+(?:\.\d+)?)\s*%\s*(?:of)?\s*(\d+(?:\.\d+)?)/);if(pct){let value=Number(pct[1])*Number(pct[2])/100;trace=`AGENT → calculator(percent: ${pct[1]}, number: ${pct[2]})\nTOOL → ${value}`;return {trace,text:`${pct[1]}% of ${pct[2]} is ${value}.`};}}
if(mode==='agent'&&p.tools.notes&&/(remember|save note|note that)/.test(lower)){let note=q.replace(/.*?(remember|save note|note that)\s*/i,'');p.notes.push(note);save();return {trace:'AGENT → notes.save(...)\nTOOL → saved',text:`Saved this note: “${note}”`};}
if(mode==='agent'&&p.tools.tasks&&/(add task|create task|remind me)/.test(lower)){let task=q.replace(/.*?(add task|create task|remind me)\s*/i,'');p.tasks.push({text:task,done:false});save();return {trace:'AGENT → tasks.create(...)\nTOOL → saved',text:`Added a task: “${task}”`};}
let isSw=/\b(naomba|nifafanulie|nisaidie|kwa|kiswahili|habari|nina)/i.test(q);let answer;if(mode==='base')answer=isSw?'Ninaweza kusaidia kueleza hilo. Tafadhali niambie zaidi kuhusu unachotaka kujua.':'Here is a general explanation. Please share more context so I can make it more useful.';else {let example=p.examples.find(x=>tokensOverlap(q,x.input)>0)||p.examples[0];let topic=q.replace(/[?.!]/g,'').slice(0,100);answer=isSw?`Kwa ufupi: ${example?example.output:'tunaanza na wazo kuu, kisha tunatumia mfano rahisi.'}\n\nJe, ungependa nifafanue sehemu gani zaidi?`:`${example?example.output:'Here is the main idea: start with a simple explanation, then apply it to your question.'}\n\nFor your question about “${topic}”, I would begin with the key idea and one practical example. ${close(p)}`;}return {trace,text:answer};}
function tokensOverlap(a,b){let x=new Set(a.toLowerCase().match(/[a-z]{4,}/g)||[]);return (b.toLowerCase().match(/[a-z]{4,}/g)||[]).filter(w=>x.has(w)).length;}
function close(p){return /ask|question|checking/i.test(p.behavior)?'What part would you like to explore next?':'';}
function finishLab(id,next){complete(id);save();go(next);}
function dashboard(){let ps=store.projects;return `${header('MY AI AGENTS','Your AI agent workshop.','Each agent has a clear job, model configuration, instructions and tools. Start another agent from one of the three presets.')}
<div class="actions"><button class="button" onclick="newProject()">+ Create another agent</button><button class="button ghost" onclick="exportAll()">Export all projects</button></div><div class="grid">${ps.map(p=>`<div class="card"><div class="eyebrow">${p.model?'AGENT SAVED':'IN PROGRESS'}</div><h2>${esc(p.name||'Untitled agent')}</h2><p>${esc(p.purpose||'No purpose defined yet.')}</p><div class="mini"><div><span>Setup</span><b>${p.model?'Ready':'Not assembled'}</b></div><div><span>Examples</span><b>${p.examples.length}</b></div><div><span>Tools</span><b>${countTools(p)}</b></div></div><div class="actions"><button class="button" onclick="openProject('${p.id}')">Open</button><button class="button danger" onclick="deleteProject('${p.id}')">Delete</button></div></div>`).join('')||'<div class="card"><p class="empty">No projects yet.</p></div>'}</div>
<div class="card"><h2>How many AI agents can you make?</h2><p>You can create several agent projects from the three starting ideas. An agent combines an existing model, instructions, information and tools. Local projects save a practice setup; live model answers require a connected model service. Training a new model is not required.</p><div class="grid3"><div><b>Preset it</b><p class="muted">Start as a Biology tutor, Business helper or Personal coach.</p></div><div><b>Guide its answers</b><p class="muted">Explore suggested examples, preset instructions and temperature.</p></div><div><b>Give it actions</b><p class="muted">Enable knowledge search, calculator, notes, and task tools independently.</p></div></div></div>`;}
function newProject(){let p=defaultProject();store.projects.push(p);store.active=p.id;store.page='intro';save();render();}
function openProject(id){store.active=id;store.page='intro';save();render();}
function deleteProject(id){if(!confirm('Delete this local AI project? This cannot be undone.'))return;store.projects=store.projects.filter(p=>p.id!==id);if(store.active===id)store.active=store.projects[0]?.id||null;save();render();}
function download(filename,data){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=filename;a.click();URL.revokeObjectURL(a.href);}
function exportProject(){let p=active();if(!p)return;download(`${(p.name||'my-ai').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-export.json`,{manifest:{format:'build-your-ai-export',exportedAt:new Date().toISOString(),agentTruth:'Existing AI + saved instructions, examples, reference information and tools'},project:p});}
function exportAll(){download('build-your-ai-projects.json',store.projects);}
installLearningEvents();
installExperience();
installCourseJourney();
installLessonDesign();
window.EveRealtime?.install();
render();
