/* Build Your AI local MVP.  Data stays in this browser unless it is exported. */
const KEY = 'build-your-ai-v1';
const presets = [
  {id:'tutor', icon:'🌿', title:'Biology tutor', purpose:'Help secondary-school learners understand biology clearly.', languages:'English + Swahili', behavior:'Explain simply, use everyday examples, answer in the user’s language, and ask one checking question.', samples:['Explain photosynthesis to a 14-year-old.','Nifafanulie cell division kwa Kiswahili rahisi.']},
  {id:'study', icon:'📚', title:'Study assistant', purpose:'Help students revise, practise, and build confidence.', languages:'English + Swahili', behavior:'Break work into short steps, give a worked example, then a small practice question.', samples:['Help me revise algebra for a test.','Make me a simple study plan.']},
  {id:'business', icon:'📈', title:'Business helper', purpose:'Help a small business plan, communicate, and make decisions.', languages:'English', behavior:'Be practical, concise, and ask for missing business details before guessing.', samples:['Help me price a new service.','Write a polite message to a customer.']},
  {id:'aviation', icon:'✈️', title:'Aviation compliance assistant', purpose:'Help aviation teams find and understand approved internal procedures.', languages:'English', behavior:'Use supplied sources, distinguish facts from suggestions, state uncertainty, and never replace an approved manual or regulator.', samples:['What should I check before an internal audit?','Summarise this compliance finding.']},
  {id:'writer', icon:'✍️', title:'Writing assistant', purpose:'Help people plan, improve, and adapt clear writing.', languages:'English + Swahili', behavior:'Preserve the author’s meaning, offer clear alternatives, and explain important edits briefly.', samples:['Improve this email without changing my meaning.','Nisaidie kuandika ujumbe wa heshima.']},
  {id:'coach', icon:'🎯', title:'Personal coach', purpose:'Help someone define realistic goals and take a next step.', languages:'English + Swahili', behavior:'Be encouraging but direct, suggest small practical actions, and avoid medical or professional claims.', samples:['Help me break a large goal into steps.','Ninaahirisha kazi; nianzie wapi?']}
];
const labs = [
  ['intro','Start here'],['lab1','Day 1 · What is AI?'],['lab2','Day 2 · Tokens'],['lab3','Day 3 · Examples'],['lab4','Day 4 · Behaviour'],['lab5','Day 5 · Model'],['lab6','Day 6 · Tools'],['lab7','Day 7 · Launch'],['dashboard','My AIs']
];
let store = load();
function defaultProject(){return {id:crypto.randomUUID(),name:'',purpose:'',preset:'',languages:'English',samples:[],examples:[],evaluation:[],knowledge:[],behavior:'Explain clearly and honestly.',temperature:.35,tools:{calculator:true,knowledge:false,notes:false,tasks:false},notes:[],tasks:[],model:null,createdAt:new Date().toISOString(),completed:[],guidance:{style:'auto',detail:'short',dailyMode:true,startedAt:null,voiceReplies:true,helpDay:null,understoodDays:[],interests:{},day1Step:1,day1LessonVersion:2},teacherMessages:[]};}
function normaliseProject(p){p.guidance??={style:'auto',detail:'short',dailyMode:true,startedAt:null,voiceReplies:true,helpDay:null,understoodDays:[],interests:{}};p.guidance.style='auto';if(p.guidance.day1LessonVersion!==2){p.guidance.day1LessonVersion=2;p.guidance.day1Step=1;p.guidance.humanGuess='';p.guidance.day1AIChoice='';p.guidance.lessonMoment=null;}p.guidance.day1Step??=1;p.guidance.voiceReplies??=true;p.guidance.understoodDays??=[];p.guidance.interests??={};p.guidance.eveHistory??=[];p.guidance.learnerName??='';p.guidance.awaitingName??=false;p.guidance.eveWelcomes??={};p.teacherMessages??=[];p.tools??={calculator:true,knowledge:false,notes:false,tasks:false};return p;}
function load(){try {let x=JSON.parse(localStorage.getItem(KEY));if(x&&x.projects){x.projects.forEach(normaliseProject);return x;}return {projects:[],active:null,page:'intro'};}catch{return {projects:[],active:null,page:'intro'};}}
function save(){localStorage.setItem(KEY,JSON.stringify(store));}
function active(){let p=store.projects.find(p=>p.id===store.active);return p&&normaliseProject(p);}
function project(){let p=active(); if(!p){p=defaultProject();store.projects.push(p);store.active=p.id;save();}return p;}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(msg){document.querySelector('.toast')?.remove();let e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.append(e);setTimeout(()=>e.remove(),2600);}
function complete(id){let p=project();if(!p.completed.includes(id))p.completed.push(id);save();}
function labDay(page){let n=Number((page||'').replace('lab',''));return Number.isInteger(n)&&n>=1&&n<=7?n:null;}
function availableDay(p){if(!p?.guidance?.dailyMode||!p?.guidance?.startedAt)return 7;let start=new Date(p.guidance.startedAt);let now=new Date();return Math.max(1,Math.min(7,Math.floor((now-start)/86400000)+1));}
function canOpen(page){let day=labDay(page),p=active();return !day||day<=availableDay(p);}
function go(page){if(!canOpen(page)){toast(`Day ${labDay(page)} opens tomorrow. Today, focus on one small step.`);return;}store.page=page;save();render();window.scrollTo({top:0,behavior:'smooth'});}
function baseName(p){return p.name||'Your AI';}
function countTools(p){return Object.values(p.tools).filter(Boolean).length;}
function panel(){let p=active();if(!p)return '';let pct=Math.round((p.completed.length/7)*100);return `<aside class="ai-panel"><h2>MY AI</h2><div class="status"><i class="dot"></i>${p.model?'Model ready':'Building'}</div><div class="progress"><i style="width:${pct}%"></i></div><div class="fineprint">${p.completed.length}/7 labs saved</div><div class="mini"><div><span>Name</span><b>${esc(p.name||'Not chosen')}</b></div><div><span>Purpose</span><b>${esc(p.purpose?short(p.purpose,25):'Not chosen')}</b></div><div><span>Languages</span><b>${esc(p.languages)}</b></div><div><span>Examples</span><b>${p.examples.length}</b></div><div><span>Model</span><b>${esc(p.model?.name||'Not created')}</b></div><div><span>Knowledge</span><b>${p.knowledge.length} sources</b></div><div><span>Tools</span><b>${countTools(p)}</b></div></div><div class="panel-actions"><button class="button ghost" onclick="exportProject()">Export this AI</button><button class="button secondary" onclick="go('dashboard')">All my AIs</button></div></aside>`;}
function short(s,n){return s.length>n?s.slice(0,n-1)+'…':s;}
function nav(){let p=active();return `<aside class="sidebar"><div class="brand">AI 102</div><div class="tagline">Build your own AI, one day at a time.</div><nav class="lab-nav">${labs.map(([id,label])=>{let locked=!canOpen(id);return `<button class="nav-item ${store.page===id?'active':''} ${p?.completed.includes(id)?'done':''} ${locked?'locked':''}" onclick="go('${id}')"><i class="nav-num">${id==='intro'?'◎':id==='dashboard'?'◫':id==='teacher'?'?':locked?'🔒':labDay(id)||label[0]}</i><span>${label}</span></button>`}).join('')}</nav><div class="side-foot">Learn slowly. Eve is here when you need her.</div></aside>`;}
function layout(content){let p=active(),day=availableDay(p);document.querySelector('#app').innerHTML=`<div class="shell">${nav()}<main><div class="topbar"><b>AI 102</b></div>${p?.guidance?.dailyMode&&store.page!=='intro'&&store.page!=='dashboard'?`<div class="daily-banner"><b>Today: Day ${day} of 7</b><span>One small lab is enough.</span></div>`:''}${content}</main>${panel()}</div>`;}
function header(kicker,title,lead){let day=labDay(store.page);return `<div class="eyebrow">${kicker}</div><h1 class="title">${title}</h1><p class="lead">${lead}</p>${day?labCoach(day):''}`;}
function render(){let p=project();if(!p.guidance.learnerName&&store.page!=='intro')store.page='intro';let pages={intro,lab1,lab2,lab3,lab4,lab5,lab6,lab7,dashboard};layout((pages[store.page]||intro)());setTimeout(()=>{tokenize();temperaturePreview();maybeWelcomeEve();},0);}

function intro(){let p=project();if(!p.guidance.learnerName)return `<section class="course-welcome"><div class="eyebrow">AI 102 · BUILD YOUR OWN AI</div><h1>${p.guidance.awaitingName?'Eve would love to know your name.':'Welcome. Eve is ready to meet you.'}</h1><p>${p.guidance.awaitingName?'Press the button below and say your name.':'She will guide you through this course, one small lesson at a time.'}</p>${p.guidance.awaitingName?eveVoiceButton(0):'<button class="button" onclick="startAI102()">Start AI 102</button>'}</section>`;return `${header('WELCOME','Let’s build your AI slowly.','You will make a helpful AI by choosing its job, showing it good answers, and giving it useful tools.')}
<div class="daily-banner"><b>Today’s only job</b><span>Choose a starting idea, give your AI a name, then press “Save my blueprint.”</span></div>
<div class="card"><h2>Choose a starting point</h2><p class="muted">A preset gives you sensible first settings. You can change every part later.</p><div class="grid3">${presets.map(x=>`<button class="choice ${p.preset===x.id?'selected':''}" onclick="choosePreset('${x.id}')"><strong>${x.icon} ${x.title}</strong><small>${esc(x.purpose)}</small></button>`).join('')}<button class="choice ${p.preset==='custom'?'selected':''}" onclick="choosePreset('custom')"><strong>✨ Something else</strong><small>Start with a blank, flexible AI.</small></button></div></div>
<div class="card"><div class="split"><div class="field"><label>What will your AI help with?</label><textarea id="purpose" placeholder="For example: Help Form Two students understand biology.">${esc(p.purpose)}</textarea></div><div class="stack"><div class="field"><label>Give it a working name</label><input id="name" value="${esc(p.name)}" placeholder="For example: Mwalimu" /></div><div class="field"><label>Languages</label><select id="languages"><option ${p.languages==='English'?'selected':''}>English</option><option ${p.languages==='English + Swahili'?'selected':''}>English + Swahili</option><option ${p.languages==='Swahili'?'selected':''}>Swahili</option><option ${p.languages==='Other / mixed'?'selected':''}>Other / mixed</option></select></div></div></div><div class="actions"><button class="button" onclick="saveBlueprint()">Save my blueprint →</button></div></div>
<div class="card"><h3>What your finished AI can do</h3><div class="grid3"><div><b>Answer your way</b><p class="muted">You show it examples of the kind of answers you like.</p></div><div><b>Use your notes</b><p class="muted">You can add useful information for it to look up.</p></div><div><b>Use simple tools</b><p class="muted">It can calculate, save notes, and make tasks.</p></div></div></div>`;}
function choosePreset(id){let p=project();p.preset=id;if(id!=='custom'){let x=presets.find(a=>a.id===id);p.name=p.name||x.title.split(' ').map(w=>w[0].toUpperCase()+w.slice(1)).join('');p.purpose=x.purpose;p.languages=x.languages;p.behavior=x.behavior;p.samples=x.samples;} else {p.purpose='';p.name='';p.samples=[];}save();render();}
function setTeachingStyle(style){project().guidance.style=style;save();toast('Eve will guide you in that way.');}
function setDetail(detail){project().guidance.detail=detail;save();toast(detail==='short'?'Short explanations selected.':'A little more help selected.');}
function saveBlueprint(){let p=project();p.purpose=document.querySelector('#purpose').value.trim();p.name=document.querySelector('#name').value.trim();p.languages=document.querySelector('#languages').value;if(!p.purpose||!p.name){toast('Add a name and a clear purpose first.');return;}p.guidance.startedAt??=new Date().toISOString();complete('intro');save();go('lab1');}

function lab1(){
  let p=project(),step=p.guidance.day1Step,choice=p.guidance.day1AIChoice||'',body;
  if(step===1) body=`<div class="card"><div class="step-label">STEP 1 OF 4 · YOU GUESS FIRST</div><h2>What do you think comes next?</h2><div class="big-sentence">I am hungry. I want to eat …</div><p>Write one thing you would guess. There is no wrong answer.</p><input id="human-guess" placeholder="I would say…" value="${esc(p.guidance.humanGuess||'')}"><div class="actions"><button class="button" onclick="revealAIGuess()">Now let AI try</button></div></div>`;
  else if(step===2) body=`<div class="card"><div class="step-label">STEP 2 OF 4 · AI MAKES A BEST GUESS</div><h2>Let AI make its guess</h2><div class="big-sentence">I am hungry. I want to eat …</div><p>AI looks at the words you gave it. It has practised finding patterns in many examples, then makes one best guess.</p><div class="actions"><button class="button" onclick="oneToken()">Let AI make a guess</button></div></div>`;
  else if(step===3) body=`<div class="card"><div class="step-label">STEP 3 OF 4 · PAUSE AND NOTICE</div><h2>AI guessed: ${esc(choice)}</h2><div class="big-sentence">I am hungry. I want to eat ${esc(choice)}.</div><p>It did not know what you truly want to eat. It made a quick best guess from patterns it learned and the clues in your sentence.</p><div class="actions"><button class="button" onclick="advanceDay1(4)">Next: give AI a better clue</button></div></div>`;
  else body=day1Practice();
  return `${header('DAY 1 · WHAT IS AI?','AI is a pattern-finding helper.','Today you will see that AI learns from examples, uses the clues you give it, and makes a best guess. It does not think or know things exactly like a person.')}${body}`;
}
function day1Practice(){return `<div class="card"><div class="step-label">STEP 4 OF 4 · PRACTISE WITH EVE</div><h2>Your turn: give AI a better clue</h2><p>Add a clue — for example <b>after football practice</b>, <b>something sweet</b>, or <b>for breakfast</b>. Watch the likely answer change.</p><div class="field"><label>Make your own sentence</label><input id="prediction-input" value="I am hungry. I want to eat" oninput="predictionBars()"></div><div id="prediction-result" class="bars">${barHTML([['rice',46],['fruit',22],['bread',12],['pasta',8]])}</div><div class="eve-example"><b>Exercise 1 · Change the clue</b><p>Add a clue and look at the likely answer. Then tell Eve you noticed the change.</p><button class="button secondary" onclick="checkDay1Clue()">I added a clue</button><p id="day1-clue-result" class="fineprint"></p></div><div class="eve-example"><b>Exercise 2 · One tiny question</b><p>Why did the likely answer change?</p><div class="actions"><button class="button secondary" onclick="answerDay1Reflection(true)">Because the new words gave AI better clues</button><button class="button ghost" onclick="answerDay1Reflection(false)">Because AI knows the future</button></div><p id="day1-reflection-result" class="fineprint"></p></div><p><b>Remember:</b> AI learns patterns from examples and uses your words as clues. Tomorrow Eve will show you the small pieces of text AI works with. They are called tokens.</p><div class="actions"><button class="button" onclick="finishLab('lab1','lab2')">Finish Day 1</button></div></div>`;}
function barHTML(rows){return rows.map(([t,n],i)=>`<div class="bar-row"><span class="mono">${esc(t)}</span><div class="bar"><i style="width:${n}%"></i></div><b>${i===0?'likely':i===1?'possible':'less likely'}</b></div>`).join('');}
function predictionBars(){let s=document.querySelector('#prediction-input').value.toLowerCase();let rows=s.includes('football')?[['rice',48],['chips',20],['fruit',14],['water',7]]:s.includes('sweet')?[['fruit',44],['cake',26],['ice cream',16],['bread',5]]:s.includes('breakfast')?[['eggs',42],['bread',27],['porridge',17],['rice',5]]:[['rice',46],['fruit',22],['bread',12],['pasta',8]];document.querySelector('#prediction-result').innerHTML=barHTML(rows);}
function checkDay1Clue(){let value=document.querySelector('#prediction-input').value.trim().toLowerCase(),result=document.querySelector('#day1-clue-result');if(value==='i am hungry. i want to eat'||value.length<30){result.textContent='Try adding one more useful clue first — for example “after football practice” or “something sweet”.';return;}result.textContent='✓ Great noticing. Your extra words changed the clues AI used, so a different answer can become most likely.';}
function answerDay1Reflection(correct){let result=document.querySelector('#day1-reflection-result');result.textContent=correct?'✓ Exactly. AI does not know the future — it uses the clues you give it to make its best next guess.':'Almost. AI does not know the future. It changed its guess because your new words gave it better clues.';}
function revealAIGuess(){let p=project(),input=document.querySelector('#human-guess');p.guidance.humanGuess=input?.value.trim()||'';p.guidance.day1Step=2;save();render();}
function advanceDay1(step){let p=project();p.guidance.day1Step=step;save();render();}
function addPrediction(){let e=document.querySelector('#prediction-input');let first=document.querySelector('#prediction-result .mono').textContent;e.value+=' '+first;project().guidance.predictionSentence=e.value;save();predictionBars();}
function oneToken(){let p=project(),piece=(['rice','fruit','bread'][Math.floor(Math.random()*3)]);p.guidance.day1AIChoice=piece;p.guidance.day1Step=3;p.guidance.lessonMoment={day:1,piece,question:null};save();render();}

function lab2(){let p=project();return `${header('DAY 2 · SMALL PIECES','What is a token?','A token is a small piece of writing that AI reads. It can be a whole word, part of a word, or a sign like “!” or “,”.')}
<div class="card"><h2>See the small pieces</h2><p><b>Example:</b> “Hello!” can become two pieces: <span class="token">Hello</span> <span class="token">!</span></p><div class="field"><label>Type anything</label><textarea id="token-text" oninput="tokenize()">${esc(p.samples[1]||'Habari, naomba unisaidie kujifunza biology.')}</textarea></div><div id="tokens"></div><p id="token-count" class="muted"></p></div>
<div class="card"><h2>Who will your AI speak with?</h2><div class="field"><label>Two typical questions users might ask</label><div class="split"><input id="sample1" value="${esc(p.samples[0]||'Explain photosynthesis simply.')}" /><input id="sample2" value="${esc(p.samples[1]||'Nifafanulie cell division kwa Kiswahili rahisi.')}" /></div></div><div class="actions"><button class="button" onclick="saveLab2()">Save language and questions →</button></div></div>`;}
function tokenize(){let e=document.querySelector('#token-text');if(!e)return;let parts=e.value.match(/[\p{L}\p{N}]+|[^\s\p{L}\p{N}]/gu)||[];document.querySelector('#tokens').innerHTML=`<div>${parts.map((x,i)=>`<span class="token" title="Token ID ${1000+i*137}">${esc(x)}</span>`).join('')}</div>`;document.querySelector('#token-count').textContent=`${e.value.length} characters → ${parts.length} tokens`}
function saveLab2(){let p=project();p.samples=[document.querySelector('#sample1').value.trim(),document.querySelector('#sample2').value.trim()].filter(Boolean);complete('lab2');save();go('lab3');}

function lab3(){let p=project();return `${header('LAB 3 · EXAMPLES','How does a model learn?','Training examples teach your model how you want it to respond. Knowledge sources give the future agent facts it can look up — they are different.')}
<div class="grid"><div class="card"><h2>Add a training example</h2><div class="field"><label>User question</label><textarea id="ex-in" placeholder="${esc(p.samples[0]||'Explain photosynthesis to a 14-year-old.')}"></textarea></div><div class="field"><label>Ideal answer</label><textarea id="ex-out" placeholder="Write the kind of answer you want your AI to learn from."></textarea></div><div class="actions"><button class="button" onclick="addExample()">Approve example</button><button class="button secondary" onclick="useSuggestedExample()">Use a suggested example</button></div></div><div class="card"><h2>Your approved examples <span class="pill">${p.examples.length}</span></h2><div id="example-list">${examplesHTML(p)}</div></div></div>
<div class="card"><h2>Knowledge library</h2><p class="muted">Paste a reliable note, procedure, or fact. Your agent can search it later; it will not be added to model training.</p><div class="field"><label>Source title</label><input id="source-title" placeholder="For example: Biology notes — photosynthesis" /></div><div class="field"><label>Source content</label><textarea id="source-content" placeholder="Paste useful information here…"></textarea></div><div class="actions"><button class="button secondary" onclick="addKnowledge()">Add source</button><button class="button" onclick="finishLab('lab3','lab4')">Continue to behaviour →</button></div></div>`;}
function examplesHTML(p){return p.examples.length?p.examples.map((x,i)=>`<div class="list-card"><b>${esc(short(x.input,62))}</b><p>${esc(short(x.output,140))}</p><button class="button danger" onclick="removeExample(${i})">Remove</button></div>`).join(''):'<p class="empty">No approved examples yet. Add at least three before creating a model.</p>';}
function addExample(){let a=document.querySelector('#ex-in').value.trim(),b=document.querySelector('#ex-out').value.trim();if(!a||!b){toast('Add both a question and an ideal answer.');return;}let p=project();p.examples.push({input:a,output:b,author:'Learner approved'});save();render();}
function useSuggestedExample(){let p=project(),q=p.samples[p.examples.length%Math.max(p.samples.length,1)]||'Explain this clearly.';document.querySelector('#ex-in').value=q;document.querySelector('#ex-out').value=`Here is a clear explanation. Start with the main idea, then use a simple example. If any part is confusing, tell me which part and I will explain it another way.`;}
function removeExample(i){project().examples.splice(i,1);save();render();}
function addKnowledge(){let title=document.querySelector('#source-title').value.trim(),content=document.querySelector('#source-content').value.trim();if(!title||!content){toast('Give the source a title and some content.');return;}project().knowledge.push({title,content});save();toast('Knowledge source saved.');render();}

function lab4(){let p=project();return `${header('LAB 4 · BEHAVIOUR','Why does AI behave differently?','Instructions and generation settings steer a model without changing its weights. You can also add examples to teach a pattern more deeply.')}
<div class="grid"><div class="card"><h2>Focused or creative?</h2><p class="muted">Temperature controls how predictable the next token choices are.</p><div class="range-line"><b>Focused</b><input type="range" min="0" max="1.3" step=".1" value="${p.temperature}" id="temp" oninput="temperaturePreview()"><b>Creative</b></div><p>Temperature: <b id="temp-value">${p.temperature}</b></p><div id="temp-answer" class="answer"></div></div><div class="card"><h2>Write the behaviour rules</h2><div class="field"><label>How should ${esc(baseName(p))} answer?</label><textarea id="behavior">${esc(p.behavior)}</textarea></div><p class="fineprint">Good rules are observable: “keep the first answer under 150 words” is more useful than “be helpful.”</p></div></div>
<div class="card"><h2>Hold-out evaluation questions</h2><p class="muted">These do not become training data. They test whether your model can generalise.</p><div class="split"><input id="eval1" value="${esc(p.evaluation[0]||p.samples[0]||'Explain a difficult concept simply.')}" /><input id="eval2" value="${esc(p.evaluation[1]||p.samples[1]||'Give a helpful answer in Swahili.')}" /></div><div class="actions"><button class="button" onclick="saveLab4()">Save behaviour and tests →</button></div></div>`;}
function temperaturePreview(){let v=Number(document.querySelector('#temp').value),t=v<.35?'DNA is like an instruction manual stored inside every cell.':v<.8?'Think of DNA as a recipe book that tells cells how to build and run a living thing.':'Imagine every cell holding a tiny library of blueprints; DNA is the collection of pages that helps life keep its shape.';document.querySelector('#temp-value').textContent=v.toFixed(1);document.querySelector('#temp-answer').textContent=t;}
function saveLab4(){let p=project();p.temperature=Number(document.querySelector('#temp').value);p.behavior=document.querySelector('#behavior').value.trim()||p.behavior;p.evaluation=[document.querySelector('#eval1').value.trim(),document.querySelector('#eval2').value.trim()].filter(Boolean);complete('lab4');save();go('lab5');}

function lab5(){let p=project(), ready=p.examples.length>=3, cloud=window.BuildAICloud?.enabled();return `${header('LAB 5 · MODEL','Create your model version.','This makes an immutable learner model: a shared base checkpoint plus your approved examples and generation configuration.')}
<div class="card"><div class="grid3"><div><span class="muted">Name</span><h2>${esc(p.model?.name||`${baseName(p)}-1`)}</h2></div><div><span class="muted">Base model</span><h2>${cloud?'GPU base model':'Open model · 4B'}</h2></div><div><span class="muted">Approved examples</span><h2>${p.examples.length}</h2></div></div><p>${ready?'<span class="success">✓ Your dataset meets this prototype’s minimum of 3 examples.</span>':'<span class="warning">Add at least 3 approved examples in Lab 3 to enable model creation.</span>'}</p>${p.training?`<div class="answer">GPU training job: <b>${esc(p.training.status)}</b><br><span class="fineprint">${esc(p.training.message||'Your queued GPU worker is preparing the learner adapter.')}</span></div>`:''}<div class="actions"><button class="button" ${ready||p.training?'':'disabled'} onclick="${p.training?'checkTraining()':'createModel()'}">${p.training?'Check training progress':p.model?'Create a new version':'Create '+esc(baseName(p))+'-1'}</button>${p.model?'<button class="button ghost" onclick="go(\'lab7\')">Open my agent</button>':''}</div><p class="fineprint">${cloud?'GPU mode: training is a real queued LoRA job.':'Local mode: training is an educational simulation. Connect the GPU backend to make it real.'}</p></div>
${p.model?evaluationHTML(p):`<div class="card"><h2>What happens when you create it?</h2><div class="grid3"><div><b>1. Starting model</b><p class="muted">The open base checkpoint is kept frozen.</p></div><div><b>2. Your adapter</b><p class="muted">Production uses a small LoRA adapter trained on approved examples.</p></div><div><b>3. Evaluation</b><p class="muted">The same held-out questions compare base and your model.</p></div></div></div>`}`;}
async function createModel(){let p=project();if(window.BuildAICloud?.enabled()){try{let job=await window.BuildAICloud.startTraining(p);p.training={id:job.id,status:job.status,message:'Queued on the GPU training worker.'};save();toast('Real GPU training job queued.');render();}catch(error){toast(error.message);};return;}let version=(p.model?.version||0)+1;p.model={name:`${baseName(p)}-${version}`,version,base:'Open model · 4B',createdAt:new Date().toISOString(),examples:p.examples.length};complete('lab5');save();toast('Model version created and evaluated.');render();}
async function checkTraining(){let p=project();if(!p.training)return;try{let job=await window.BuildAICloud.trainingStatus(p.training.id);p.training.status=job.status;p.training.message=job.message||'';if(job.status==='COMPLETED'){p.model={name:job.model_name,version:job.version,base:job.base_model,adapterKey:job.adapter_key,evaluation:job.evaluation||[],createdAt:new Date().toISOString(),examples:p.examples.length};p.training=null;complete('lab5');toast('Your real GPU model is ready.');}else if(job.status==='FAILED'){toast(job.message||'The training job failed.');}save();render();}catch(error){toast(error.message);}}
function evaluationHTML(p){let real=p.model?.evaluation?.length,qs=real?p.model.evaluation:(p.evaluation.length?p.evaluation:[p.samples[0]||'Explain this simply.',p.samples[1]||'Give a useful answer.']);return `<div class="card"><h2>Before / after evaluation</h2><p class="muted">${real?'These are real held-out GPU outputs from the starting checkpoint and your LoRA adapter.':'Blind evaluation asks whether the learner-model response is preferred for your stated purpose. In local mode, outputs are transparent educational simulations.'}</p><div class="metric">${Math.min(qs.length,2)}/${qs.length} <span class="muted" style="font-size:14px">learner-model responses preferred</span></div>${qs.map((q,i)=>{let prompt=real?q.prompt:q;let base=real?q.base:generateReply(q,p,'base').text;let model=real?q.model:generateReply(q,p,'model').text;return `<div class="compare"><div><h3>STARTING MODEL</h3><p class="fineprint">${esc(prompt)}</p><div class="answer">${esc(base)}</div></div><div class="result-good"><h3>MY MODEL · ${esc(p.model.name)}</h3><div class="answer">${esc(model)}</div></div></div>`}).join('')}<div class="actions"><button class="button" onclick="go('lab6')">Give your model tools →</button></div></div>`;}

function lab6(){let p=project();let tool=[['calculator','Calculator','Solves arithmetic, conversions and simple calculations.'],['knowledge','Knowledge search','Looks through your saved knowledge sources.'],['notes','Notes','Saves a short note for this AI project.'],['tasks','Tasks','Creates and checks off simple tasks.']];return `${header('LAB 6 · TOOLS','A model can talk. Can it act?','Your agent decides when to use a tool, shows the action taken, and then uses the result in its answer.')}
<div class="grid">${tool.map(([id,n,d])=>`<button class="choice ${p.tools[id]?'selected':''}" onclick="toggleTool('${id}')"><strong>${p.tools[id]?'✓':'○'} ${n}</strong><small>${d}</small></button>`).join('')}</div><div class="card"><h2>Tool trace preview</h2><div class="trace">USER → “What is 25 × 4?”<br>AGENT → tool call: calculator({ expression: "25 * 4" })<br>TOOL → 100<br>AGENT → “25 × 4 = 100.”</div><p class="fineprint">The agent only has access to tools you enable. It never pretends it used a tool when it did not.</p><div class="actions"><button class="button" onclick="finishLab('lab6','lab7')">Save my tools →</button></div></div>`;}
function toggleTool(id){let p=project();p.tools[id]=!p.tools[id];save();render();}

function lab7(){let p=project();if(!p.model)return `${header('LAB 7 · LAUNCH','Create your model first.','Your agent needs a model version before it can launch.')}<div class="card"><button class="button" onclick="go('lab5')">Go to model creation</button></div>`;return `${header('LAB 7 · LAUNCH','Meet ${esc(baseName(p))}.','Your agent is ready: model version, instructions, knowledge, and selected tools — all visible and editable.')}
<div class="grid"><div class="card"><h2>Agent playground</h2><div class="chat" id="chat"><div class="bubble agent">Hello — I’m ${esc(baseName(p))}. ${esc(firstBehavior(p))}</div></div><div class="split" style="margin-top:12px"><input id="chat-input" placeholder="Ask your AI something…" onkeydown="if(event.key==='Enter')sendChat()" /><button class="button" onclick="sendChat()">Send</button></div></div><div class="card"><h2>Agent settings</h2><div class="mini"><div><span>Model</span><b>${esc(p.model.name)}</b></div><div><span>Knowledge</span><b>${p.knowledge.length} sources</b></div><div><span>Tools</span><b>${countTools(p)} enabled</b></div><div><span>Temperature</span><b>${p.temperature.toFixed(1)}</b></div></div><div class="field"><label>Agent instructions</label><textarea id="agent-behavior">${esc(p.behavior)}</textarea></div><div class="actions"><button class="button secondary" onclick="saveAgentRules()">Save instructions</button><button class="button" onclick="launch()">Launch my AI</button></div></div></div>
<div class="card"><h2>Try these test scenarios</h2><div class="grid3"><div><b>Normal answer</b><p>${esc(p.samples[0]||'Ask a typical user question.')}</p></div><div><b>Knowledge lookup</b><p>${p.knowledge.length?'Ask something that appears in your library.':'Add a source in Lab 3, then test it here.'}</p></div><div><b>Tool usage</b><p>Ask “What is 15% of 800?” to test the calculator.</p></div></div></div>`;}
function firstBehavior(p){return (p.behavior||'I will help clearly.').split(/[.!]/)[0]+'.';}
function saveAgentRules(){project().behavior=document.querySelector('#agent-behavior').value.trim();save();toast('Agent instructions saved.');}
function launch(){complete('lab7');save();toast(`${baseName(project())} is live in this browser.`);go('dashboard');}
const lessonNotes={
  1:{name:'What is AI?',simple:'AI is a computer helper that has practised finding patterns in many examples. It uses the clues in your words to make a best guess.',example:'If you hear “I am hungry. I want to eat …”, you may expect “rice” or “fruit”. AI makes a similar best guess from patterns.',try:'Try one sentence and add a useful clue. Notice how the likely answer changes.'},
  2:{name:'Tokens',simple:'Before AI can work with a sentence, it breaks the sentence into small pieces called tokens.',example:'“I love biology!” may become small pieces like “I”, “ love”, “ biology”, and “!”.',try:'Paste one short sentence in the Token Lab. Do not worry about the numbers—just look at the coloured pieces.'},
  3:{name:'Examples',simple:'Examples are like showing your AI what a good answer looks like. They teach its response style, not all the facts it should know.',example:'Question: “What is a cell?” Good answer: “A cell is a tiny building block of life.”',try:'Make one simple question-and-answer pair. One good example is enough for today.'},
  4:{name:'Behaviour',simple:'The same AI can sound different depending on the instructions and how creative you let it be.',example:'A low creativity setting gives a focused answer. A higher one may use a more imaginative example.',try:'Choose one rule you want: “Use simple words” is a perfect start.'},
  5:{name:'Your model',simple:'Today your approved examples become a model version. The big starting model stays mostly unchanged; a small learning layer is added.',example:'Think of the base model as a textbook and your small adapter as your own notes in the margin.',try:'Look at your examples. If they show the answers you want, you are ready.'},
  6:{name:'Tools',simple:'A model can talk, but tools help it do small jobs such as calculate, search notes, or save a task.',example:'For “What is 15% of 800?”, the agent can use its calculator instead of guessing.',try:'Turn on one tool only. Calculator is a good first choice.'},
  7:{name:'Launch',simple:'Your AI agent brings together your model, instructions, knowledge, and tools in one place.',example:'A tutor can explain a topic, search your notes, then ask a checking question.',try:'Ask one normal question in the playground. You do not need to test everything today.'}
};
function labCoach(day){return eveVoiceButton(day);}
function eveVoiceButton(day){return `<button class="eve-orb" id="eve-orb" onclick="useEve(${day})" aria-label="Talk to Eve"><span>✦</span><small>Talk to Eve</small></button>`;}
function evePayload(day,message){let p=project(),lesson=lessonNotes[day]||lessonNotes[1],turns=(p.guidance.eveHistory||[]).slice(-12).map(turn=>({role:turn.role,text:turn.text}));return {lesson:lesson.name,lesson_summary:lesson.simple,activity:lesson.try,learner_message:message,recent_turns:turns,learner_interest:Object.values(p.guidance.interests||{}).join(', '),learner_name:p.guidance.learnerName,language:p.languages};}
function saveEveTurn(day,role,text){let p=project();p.guidance.eveHistory.push({day,role,text,at:Date.now()});p.guidance.eveHistory=p.guidance.eveHistory.slice(-40);save();}
async function sendLiveEve(day,message){saveEveTurn(day,'learner',message);try{let reply=await window.BuildAICloud.teacherReply(evePayload(day,message));saveEveTurn(day,'eve',reply.text);playLiveEve(reply.text,day);}catch(error){toast(error.message);}}
let eveRecordingState=null,eveAudio=null,eveAudioDay=null;
function setEveOrb(day,label,icon='✦'){let button=document.querySelector('#eve-orb');if(!button)return;button.onclick=()=>useEve(day);button.innerHTML=`<span>${icon}</span><small>${label}</small>`;button.setAttribute('aria-label',label);}
function stopEve(){if(eveAudio){eveAudio.pause();eveAudio.currentTime=0;}eveAudio=null;let day=eveAudioDay||labDay(store.page)||0;eveAudioDay=null;setEveOrb(day,project().guidance.awaitingName?'Tell Eve your name':'Talk to Eve');}
async function playLiveEve(text,day){try{let audio=await window.BuildAICloud.teacherSpeech(text),sound=new Audio(`data:${audio.mime_type};base64,${audio.audio_base64}`);eveAudio=sound;eveAudioDay=day;setEveOrb(day,'Stop Eve','■');sound.onended=()=>stopEve();await sound.play();}catch(error){toast('Eve could not speak just now. Check that her teacher service is running.');}}
async function useEve(day){if(eveAudio){stopEve();return;}await toggleEveRecording(day);}
async function startAI102(){let p=project();p.guidance.awaitingName=true;save();render();await playLiveEve('Welcome to AI 102. My name is Eve. I will guide you through this journey one small day at a time. What is your name?',0);setEveOrb(0,'Tell Eve your name','🎙');}
function nameFromSpeech(text){let name=text.replace(/^(my name is|i am|i'm|this is)\s+/i,'').replace(/[^\p{L}\s'-]/gu,'').trim().split(/\s+/).slice(0,3).join(' ');return name?name.replace(/\b\p{L}/gu,letter=>letter.toUpperCase()):'';}
async function maybeWelcomeEve(){let day=labDay(store.page),p=project();if(!day||!p.guidance.learnerName)return;let today=new Date().toDateString();if(p.guidance.eveWelcomes[day]===today)return;try{let reply=await window.BuildAICloud.teacherReply(evePayload(day,`The learner has opened Day ${day}. Welcome them by name, introduce only the first small idea for today, and ask one natural thinking question.`));p.guidance.eveWelcomes[day]=today;p.guidance.eveHistory.push({day,role:'eve',text:reply.text,at:Date.now()});save();playLiveEve(reply.text,day);}catch{}}
async function toggleEveRecording(day){if(eveRecordingState){eveRecordingState.recorder.stop();setEveOrb(day,'Eve is listening…','●');return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){toast('Voice recording is not available in this browser.');return;}try{let stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[],recorder=new MediaRecorder(stream);eveRecordingState={recorder,stream,day,chunks};recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data);};recorder.onstop=async()=>{let active=eveRecordingState;eveRecordingState=null;active.stream.getTracks().forEach(track=>track.stop());try{let blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'}),language=project().languages.includes('Swahili')?'sw':'en',heard=await window.BuildAICloud.teacherTranscribe(blob,language),profile=project().guidance;if(profile.awaitingName){let name=nameFromSpeech(heard.text);if(!name){toast('Eve did not catch the name. Please try once more.');setEveOrb(day,'Tell Eve your name','🎙');return;}profile.learnerName=name;profile.awaitingName=false;if(project().completed.includes('intro'))store.page='lab1';save();render();await playLiveEve(`Lovely to meet you, ${name}. Let’s begin AI 102 together.`,day);return;}await sendLiveEve(day,heard.text);}catch(error){toast(error.message);}setEveOrb(day,'Talk to Eve');};recorder.start();setEveOrb(day,'Stop and send','■');}catch{toast('Microphone access was not allowed.');}}
function eveGuessMoment(moment){let detail=moment.question==='think'?`<p><b>Does AI think like a person?</b> No. AI does not have feelings, wants, or lived experience. It is very good at finding patterns and using them to make a helpful guess.</p>`:moment.question==='source'?`<p><b>Where did the guess come from?</b> Before you met it, AI practised on a lot of examples and learned patterns. Your sentence tells it which pattern might fit now. It is not reading the internet or someone’s mind when it guesses.</p>`:'';return `<div class="eve-moment"><b>Eve noticed something</b><p>AI guessed “${esc(moment.piece)}”. It did not know what you want. It used the words you gave it and patterns it learned to make a best guess.</p>${detail}<p><b>What would you like to understand?</b></p><div class="actions"><button class="button ghost" onclick="explainEveMoment('think')">Does AI think like me?</button><button class="button ghost" onclick="explainEveMoment('source')">Where did its guess come from?</button></div></div>`;}
function explainEveMoment(question){let p=project();if(!p.guidance.lessonMoment)return;p.guidance.lessonMoment.question=question;save();render();}
function speakEveIntro(day){if(!('speechSynthesis' in window)){toast('Voice is not available in this browser.');return;}let p=project(),lesson=lessonNotes[day],status=document.querySelector('#eve-voice-status'),intro=day===1?'Hi, my name is Eve. I will walk with you through this journey, one small day at a time. ':`Hi, I am Eve. Today is day ${day}. `;let text=`${intro}Today we are learning about ${lesson.name}. ${lesson.simple} First, try the small activity below. Then come back and tell me if it made sense.`;window.speechSynthesis.cancel();let voice=new SpeechSynthesisUtterance(text);voice.lang=p.languages.includes('Swahili')?'sw-TZ':'en-US';voice.rate=.88;voice.onstart=()=>{if(status)status.textContent='Eve is speaking…';};voice.onend=()=>{if(status)status.textContent='Eve has finished. Now try the small activity.';};voice.onerror=()=>{if(status)status.textContent='Voice could not play. Check your device volume and try again.';};window.speechSynthesis.speak(voice);}
function explainForInterest(lesson,interest){return `Think about ${interest}. ${lesson.example} We can use ${interest} as our familiar example while we learn this new idea.`;}
function understandLab(day){let p=project();if(!p.guidance.understoodDays.includes(day))p.guidance.understoodDays.push(day);p.guidance.helpDay=null;save();toast('Well done. Now try the small activity below.');render();}
function needHelpWithLab(day){let p=project();p.guidance.helpDay=day;save();render();}
function saveInterest(day){let input=document.querySelector(`#interest-${day}`),interest=input?.value.trim();if(!interest){toast('Tell Eve one thing you enjoy.');return;}let p=project();p.guidance.interests[day]=interest;p.guidance.helpDay=null;save();render();}
const videoScripts={
  1:'Habari! Today we begin with one big idea: what is AI? AI is a computer helper that practises finding patterns in examples. Try this: “I am hungry. I want to eat …” What came to your mind? AI makes a best guess from the same clues. Open Day 1 and try it. That is all for today.',
  2:'Today, AI does not see a sentence exactly as we do. It breaks it into small pieces called tokens. Open Day 2, type one sentence, and look at the coloured pieces. You do not need to understand the numbers.',
  3:'Today we teach AI with examples. Give it one question and the kind of answer you wish it would give. Think of it like showing a learner one good worked example. Make just one today.',
  4:'Today we choose how our AI behaves. Do you want it to use simple words, short answers, or everyday examples? Pick one rule. Small and clear is better than many rules.',
  5:'Today we create a model version. Your big starting model is not rebuilt; your examples create a small learning layer. Check your examples and press create when they look right.',
  6:'Today we give our AI a tool. A tool is like giving a learner a calculator or a notebook. Start with one tool: calculator. Then ask it one calculation.',
  7:'Today we bring everything together: your model, its instructions, knowledge, and tools. Ask it one normal question. Congratulations—you have created an AI agent.'
};
function teachingAnswer(p,message){let day=labDay(store.page)||availableDay(p),lesson=lessonNotes[day]||lessonNotes[1],q=(message||'').toLowerCase(),style=p.guidance.style;let core=q.includes('what')||q.includes('explain')||q.includes('understand')?lesson.simple:lesson.try;if(q.includes('example')||style==='examples')core=`${lesson.simple}\n\nExample: ${lesson.example}`;if(style==='show')core=`${lesson.simple}\n\nLook for this in the lab: ${lesson.try}`;if(style==='steps')core=`1. Open today’s small activity.\n2. Do only the first action.\n3. ${lesson.try}`;if(style==='practice')core=`${lesson.simple}\n\nTiny try: ${lesson.try}`;if(p.guidance.detail==='normal')core+=`\n\nThe important word today is “${lesson.name}.” You do not need to memorise it—just notice it.`;return core;}
function teacher(){let p=project(),day=availableDay(p),lesson=lessonNotes[day]||lessonNotes[1],messages=p.teacherMessages.length?p.teacherMessages:[{role:'teacher',text:`Hi, my name is Eve. Today we will learn one small thing: ${lesson.name}. Tell me one word that feels confusing, and I will explain only that.`}];return `${header('EVE · YOUR AI TEACHER','Talk to me. I will go at your pace.','Speak or type. I will keep answers short and adapt to how you prefer to learn.')}
<div class="card"><h2>Ask about today’s small lesson</h2><div class="voice-card"><b>🎙 Voice Teacher</b><p>Say: “show me”, “go slowly”, “give an example”, or “let me try”. I will adapt how I teach.</p><div class="actions"><button class="button" onclick="startVoiceTeacher()">🎙 Talk to your teacher</button><button class="button ${p.guidance.voiceReplies?'secondary':''}" onclick="toggleVoiceReplies()">${p.guidance.voiceReplies?'🔊 Voice replies on':'🔇 Voice replies off'}</button></div><p id="voice-status" class="fineprint">Your voice is used only for this conversation and is not saved by this local app.</p></div><div class="chat" id="teacher-chat">${messages.map(m=>`<div class="bubble ${m.role==='learner'?'me':'agent'}">${esc(m.text)}</div>`).join('')}</div><div class="actions"><button class="button secondary" onclick="quickTeacher('Explain it in the easiest way')">Simplify it</button><button class="button secondary" onclick="quickTeacher('Show me an example')">Give an example</button><button class="button secondary" onclick="quickTeacher('Let me try')">Let me try</button><button class="button ghost" onclick="go('lab${day}')">Open today’s small activity</button></div><div class="split" style="margin-top:12px"><input id="teacher-input" placeholder="What is confusing?" onkeydown="if(event.key==='Enter')askTeacher()"><button class="button" onclick="askTeacher()">Ask</button></div></div>`;}
function learningStyleFromSpeech(message){let text=message.toLowerCase();if(/show|see|picture|visual|look/.test(text))return 'show';if(/slow|step|one by one|again|polepole/.test(text))return 'steps';if(/example|real life|mfano/.test(text))return 'examples';if(/try|practice|question|jaribu/.test(text))return 'practice';return null;}
function teacherReply(message){let p=project(),heardStyle=learningStyleFromSpeech(message);if(heardStyle&&heardStyle!==p.guidance.style)p.guidance.style=heardStyle;let reply=teachingAnswer(p,message);if(heardStyle){let names={show:'showing you',steps:'small steps',examples:'everyday examples',practice:'tiny practice questions'};reply=`I heard that you may learn best with ${names[heardStyle]}. I will use that style.\n\n${reply}`;}p.teacherMessages.push({role:'learner',text:message},{role:'teacher',text:reply});save();return reply;}
function askTeacher(){let input=document.querySelector('#teacher-input'),message=input.value.trim();if(!message)return;let reply=teacherReply(message);render();if(project().guidance.voiceReplies)speakTeacher(reply);}
function quickTeacher(message){document.querySelector('#teacher-input').value=message;askTeacher();}
function showAllScripts(){let p=project();p.teacherMessages.push({role:'teacher',text:Object.entries(videoScripts).map(([day,script])=>`DAY ${day}: ${script}`).join('\n\n')});save();render();}
function toggleVoiceReplies(){let p=project();p.guidance.voiceReplies=!p.guidance.voiceReplies;save();render();}
function speakTeacher(text){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();let utterance=new SpeechSynthesisUtterance(text.replace(/\n/g,' '));let p=project();utterance.lang=p.languages.includes('Swahili')?'sw-TZ':'en-US';utterance.rate=.92;window.speechSynthesis.speak(utterance);}
function startVoiceTeacher(){let Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){toast('Voice listening is not available in this browser. You can still type to your teacher.');return;}let p=project(),status=document.querySelector('#voice-status'),recognition=new Recognition();recognition.lang=p.languages.includes('Swahili')?'sw-TZ':'en-US';recognition.interimResults=false;recognition.maxAlternatives=1;status.textContent='Listening… speak naturally.';recognition.onresult=(event)=>{let message=event.results[0][0].transcript;status.textContent=`I heard: “${message}”`;let reply=teacherReply(message);render();if(project().guidance.voiceReplies)speakTeacher(reply);};recognition.onerror=(event)=>{status.textContent=event.error==='not-allowed'?'Microphone permission was not allowed. You can type instead.':'I could not hear that. Please try again or type your question.';};recognition.start();}
async function sendChat(){let input=document.querySelector('#chat-input'),q=input.value.trim();if(!q)return;let p=project(),chat=document.querySelector('#chat');chat.insertAdjacentHTML('beforeend',`<div class="bubble me">${esc(q)}</div>`);input.value='';chat.scrollTop=chat.scrollHeight;if(window.BuildAICloud?.enabled()&&p.model?.adapterKey){try{let r=await window.BuildAICloud.chat(p,q);chat.insertAdjacentHTML('beforeend',`<div class="bubble agent">${esc(r.text)}</div>`);chat.scrollTop=chat.scrollHeight;return;}catch(error){chat.insertAdjacentHTML('beforeend',`<div class="bubble agent">The GPU service was unavailable, so I used local teaching mode. (${esc(error.message)})</div>`);}}let r=generateReply(q,p,'agent');chat.insertAdjacentHTML('beforeend',`${r.trace?`<div class="trace">${esc(r.trace)}</div>`:''}<div class="bubble agent">${esc(r.text)}</div>`);chat.scrollTop=chat.scrollHeight;}
function generateReply(q,p,mode){let lower=q.toLowerCase(), trace='';let known=p.knowledge.find(k=>k.content.toLowerCase().split(/\W+/).filter(w=>w.length>4).some(w=>lower.includes(w)));if(mode==='agent'&&p.tools.knowledge&&known){trace=`AGENT → knowledge_search(query: "${short(q,42)}")\nTOOL → found: ${known.title}`;return {trace,text:`According to “${known.title}”: ${short(known.content,500)}\n\n${close(p)}`};}
if(mode==='agent'&&p.tools.calculator&&(/\d/.test(q))){let normalized=q.replace(/[×x]/gi,'*').replace(/÷/g,'/'),expr=(normalized.match(/[\d.+*/()\-]+/g)||[]).join('').replace(/\s/g,'');if(expr&&/[+*/-]/.test(expr)){try{let value=Function('"use strict";return ('+expr+')')();trace=`AGENT → calculator(expression: "${expr}")\nTOOL → ${value}`;return {trace,text:`The result is ${value}. ${close(p)}`};}catch{}}let pct=q.match(/(\d+(?:\.\d+)?)\s*%\s*(?:of)?\s*(\d+(?:\.\d+)?)/);if(pct){let value=Number(pct[1])*Number(pct[2])/100;trace=`AGENT → calculator(percent: ${pct[1]}, number: ${pct[2]})\nTOOL → ${value}`;return {trace,text:`${pct[1]}% of ${pct[2]} is ${value}.`};}}
if(mode==='agent'&&p.tools.notes&&/(remember|save note|note that)/.test(lower)){let note=q.replace(/.*?(remember|save note|note that)\s*/i,'');p.notes.push(note);save();return {trace:'AGENT → notes.save(...)\nTOOL → saved',text:`Saved this note: “${note}”`};}
if(mode==='agent'&&p.tools.tasks&&/(add task|create task|remind me)/.test(lower)){let task=q.replace(/.*?(add task|create task|remind me)\s*/i,'');p.tasks.push({text:task,done:false});save();return {trace:'AGENT → tasks.create(...)\nTOOL → saved',text:`Added a task: “${task}”`};}
let isSw=/\b(naomba|nifafanulie|nisaidie|kwa|kiswahili|habari|nina)/i.test(q);let answer;if(mode==='base')answer=isSw?'Ninaweza kusaidia kueleza hilo. Tafadhali niambie zaidi kuhusu unachotaka kujua.':'Here is a general explanation. Please share more context so I can make it more useful.';else {let example=p.examples.find(x=>tokensOverlap(q,x.input)>0)||p.examples[0];let topic=q.replace(/[?.!]/g,'').slice(0,100);answer=isSw?`Kwa ufupi: ${example?example.output:'tunaanza na wazo kuu, kisha tunatumia mfano rahisi.'}\n\nJe, ungependa nifafanue sehemu gani zaidi?`:`${example?example.output:'Here is the main idea: start with a simple explanation, then apply it to your question.'}\n\nFor your question about “${topic}”, I would begin with the key idea and one practical example. ${close(p)}`;}return {trace,text:answer};}
function tokensOverlap(a,b){let x=new Set(a.toLowerCase().match(/[a-z]{4,}/g)||[]);return (b.toLowerCase().match(/[a-z]{4,}/g)||[]).filter(w=>x.has(w)).length;}
function close(p){return /ask|question|checking/i.test(p.behavior)?'What part would you like to explore next?':'';}
function finishLab(id,next){complete(id);save();go(next);}
function dashboard(){let ps=store.projects;return `${header('MY AIs','Your model workshop.','Each project can have as many model versions as you want. Presets are simply fast starting configurations.')}
<div class="actions"><button class="button" onclick="newProject()">+ Create another AI</button><button class="button ghost" onclick="exportAll()">Export all projects</button></div><div class="grid">${ps.map(p=>`<div class="card"><div class="eyebrow">${p.model?'MODEL READY':'IN PROGRESS'}</div><h2>${esc(p.name||'Untitled AI')}</h2><p>${esc(p.purpose||'No purpose defined yet.')}</p><div class="mini"><div><span>Versions</span><b>${p.model?.version||0}</b></div><div><span>Examples</span><b>${p.examples.length}</b></div><div><span>Tools</span><b>${countTools(p)}</b></div></div><div class="actions"><button class="button" onclick="openProject('${p.id}')">Open</button><button class="button danger" onclick="deleteProject('${p.id}')">Delete</button></div></div>`).join('')||'<div class="card"><p class="empty">No projects yet.</p></div>'}</div>
<div class="card"><h2>How many AI models can you make?</h2><p><b>Unlimited projects and model versions</b> in this prototype. Technically, each “learner model” is a <b>derivative</b>: the same shared open-weight base model plus that project’s LoRA adapter and generation settings. You are not creating a new foundation model every time.</p><div class="grid3"><div><b>Preset it</b><p class="muted">Start as a tutor, compliance assistant, business helper, writer, study assistant, coach, or custom AI.</p></div><div><b>Teach behaviour</b><p class="muted">Approve examples, choose languages, instructions, and creativity level.</p></div><div><b>Give it capabilities</b><p class="muted">Enable knowledge search, calculator, notes, and task tools independently.</p></div></div></div>`;}
function newProject(){let p=defaultProject();store.projects.push(p);store.active=p.id;store.page='intro';save();render();}
function openProject(id){store.active=id;store.page='intro';save();render();}
function deleteProject(id){if(!confirm('Delete this local AI project? This cannot be undone.'))return;store.projects=store.projects.filter(p=>p.id!==id);if(store.active===id)store.active=store.projects[0]?.id||null;save();render();}
function download(filename,data){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=filename;a.click();URL.revokeObjectURL(a.href);}
function exportProject(){let p=active();if(!p)return;download(`${(p.name||'my-ai').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-export.json`,{manifest:{format:'build-your-ai-export',exportedAt:new Date().toISOString(),modelTruth:'Base model + learner adapter/configuration + agent components'},project:p});}
function exportAll(){download('build-your-ai-projects.json',store.projects);}
render();
