const state={lab:1,name:'Mwalimu',purpose:'Teach secondary-school biology simply.',examples:0,tools:0,trained:false};
const labs={
  1:{eyebrow:'LAB 1 OF 7',title:'It predicts what comes <em>next.</em>',intro:'Try guiding a language model one piece at a time. The context changes what it thinks is likely.'},
  2:{eyebrow:'LAB 2 OF 7',title:'Your AI sees <em>pieces</em>, not sentences.',intro:'Explore how the same words become tokens, then choose the languages your AI will support.'},
  3:{eyebrow:'LAB 3 OF 7',title:'Examples teach a model <em>how</em> to respond.',intro:'Edit a model answer into the kind of response you want your AI to learn from.'},
  4:{eyebrow:'LAB 4 OF 7',title:'Define what <em>good</em> looks like.',intro:'Control creativity, shape behaviour, and create questions that stay separate from training.'},
  5:{eyebrow:'LAB 5 OF 7',title:'Create the first version of <em>your model.</em>',intro:'Your examples will train a small adapter on top of an open starting model.'},
  6:{eyebrow:'LAB 6 OF 7',title:'A model can think. An agent can <em>act.</em>',intro:'Connect knowledge and safe, visible tools to make your model useful in the world.'},
  7:{eyebrow:'LAB 7 OF 7',title:'Your AI is ready to <em>launch.</em>',intro:'Review the exact pieces you created, then bring your private agent to life.'}
};
const content={
  2:`<section class="lab-card"><span class="eyebrow">TOKENIZER MICROSCOPE</span><h2>Type something your AI might hear.</h2><textarea id="token-input" rows="3">Nifundishe kuhusu photosynthesis.</textarea><div class="token-output" id="token-output"></div><p class="hint" id="token-count">37 characters → 7 tokens</p><div class="language-choices"><button class="choice selected" data-lang="English + Swahili">English + Swahili</button><button class="choice" data-lang="English">English only</button><button class="choice" data-lang="Swahili">Swahili only</button></div></section>`,
  3:`<section class="lab-card"><span class="eyebrow">DATASET STUDIO</span><h2>Shape a great answer.</h2><div class="example-pair"><div><span>USER</span><p>Explain photosynthesis to a 14-year-old.</p></div><div><span>IDEAL RESPONSE</span><textarea id="example-answer" rows="5">Photosynthesis is how green plants make their own food using sunlight, water and air. Think of a leaf as a tiny solar-powered kitchen. Quick check: which part gives the plant energy?</textarea></div></div><div class="stage-actions"><span id="example-status">Nothing is training yet.</span><button class="primary-button" id="approve-example">Approve example <span>→</span></button></div></section>`,
  4:`<section class="lab-card"><span class="eyebrow">BEHAVIOUR STUDIO</span><h2>How should your AI sound?</h2><div class="temperature"><div><span>Focused</span><strong id="temp-value">0.4</strong><span>Creative</span></div><input type="range" min="0" max="13" value="4" id="temperature" aria-label="Creativity level" /></div><div class="behaviour-list"><label><input type="checkbox" checked /> Explain before technical vocabulary</label><label><input type="checkbox" checked /> Use everyday examples</label><label><input type="checkbox" checked /> Ask one checking question</label><label><input type="checkbox" /> Keep answers under 150 words</label></div><button class="primary-button" id="save-behaviour">Save behaviour <span>→</span></button></section>`,
  5:`<section class="training-card"><span class="eyebrow">MODEL LAB</span><div class="training-head"><div><h2>${state.name}-1</h2><p>Starting model: Qwen3.5-4B · ${Math.max(state.examples,38)} approved examples</p></div><span class="model-status" id="model-status">NOT TRAINED</span></div><div class="adapter-visual"><div class="base-block">Starting model<br><small>frozen</small></div><div class="adapter-block">Your adapter<br><small>learnable</small></div></div><div class="training-steps" id="training-steps"><p>○ Loading starting model</p><p>○ Attaching your adapter</p><p>○ Training on your examples</p><p>○ Saving ${state.name}-1</p></div><button class="primary-button" id="train-button">Create ${state.name}-1 <span>→</span></button></section>`,
  6:`<section class="lab-card"><span class="eyebrow">AGENT BUILDER</span><h2>Choose useful, visible actions.</h2><div class="tool-grid"><button class="tool-card" data-tool="Calculator"><b>⌗</b><span>Calculator</span><small>Solve numbers reliably</small></button><button class="tool-card" data-tool="Knowledge Search"><b>⌕</b><span>Knowledge Search</span><small>Look through your notes</small></button><button class="tool-card" data-tool="Notes"><b>✎</b><span>Notes</span><small>Save a useful thought</small></button><button class="tool-card" data-tool="Tasks"><b>✓</b><span>Tasks</span><small>Create a next step</small></button></div><div class="agent-preview" id="agent-preview">Your agent has no connected tools yet.</div></section>`,
  7:`<section class="launch-card"><span class="eyebrow">MY AI IS COMPLETE</span><div class="launch-orb">✦</div><h2>${state.name} is ready.</h2><p>Your model, examples, knowledge and tools are assembled into one private AI agent.</p><div class="launch-summary"><span><b>MODEL</b>${state.trained?state.name+'-1':'Create a model first'}</span><span><b>EXAMPLES</b>${state.examples} approved</span><span><b>TOOLS</b>${state.tools} connected</span></div><button class="primary-button" id="launch-button">Launch ${state.name} <span>→</span></button><p class="launch-message" id="launch-message"></p></section>`
};
function updatePanel(){document.getElementById('ai-name').textContent=state.name;document.getElementById('ai-purpose').textContent=state.purpose.replace(/^Teach /,'').replace(' simply.','');document.getElementById('progress-label').textContent=`${state.lab} of 7 labs`;document.getElementById('progress-fill').style.width=`${state.lab/7*100}%`;document.getElementById('stat-examples').textContent=`${state.examples} approved`;document.getElementById('stat-model').textContent=state.trained?state.name+'-1':'Not created';document.getElementById('stat-tools').textContent=`${state.tools} connected`;}
function drawTokens(){const input=document.getElementById('token-input');if(!input)return;const tokens=input.value.match(/[\p{L}]+|[^\s\p{L}]/gu)||[];document.getElementById('token-output').innerHTML=tokens.map((t,i)=>`<button class="token" title="Token ${i+1}">${t}</button>`).join('');document.getElementById('token-count').textContent=`${input.value.length} characters → ${tokens.length} tokens`;}
function bindLab(){document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.getElementById('stat-languages').textContent=b.dataset.lang});const token=document.getElementById('token-input');if(token){drawTokens();token.oninput=drawTokens}const approve=document.getElementById('approve-example');if(approve)approve.onclick=()=>{state.examples++;document.getElementById('example-status').textContent=`Example #${state.examples} approved for training.`;updatePanel()};const saveBehaviour=document.getElementById('save-behaviour');if(saveBehaviour)saveBehaviour.onclick=()=>{saveBehaviour.textContent='Behaviour saved ✓'};const temp=document.getElementById('temperature');if(temp)temp.oninput=()=>document.getElementById('temp-value').textContent=(temp.value/10).toFixed(1);const train=document.getElementById('train-button');if(train)train.onclick=()=>runTraining(train);document.querySelectorAll('.tool-card').forEach(tool=>tool.onclick=()=>{tool.classList.toggle('selected');state.tools=document.querySelectorAll('.tool-card.selected').length;document.getElementById('agent-preview').textContent=`Your agent can now use: ${[...document.querySelectorAll('.tool-card.selected')].map(x=>x.dataset.tool).join(', ')||'no tools yet'}.`;updatePanel()});const launch=document.getElementById('launch-button');if(launch)launch.onclick=()=>{document.getElementById('launch-message').textContent=`${state.name} is live in your private playground.`;launch.textContent='Launched ✓'}}
function runTraining(btn){btn.disabled=true;btn.textContent='Creating your model…';const steps=[...document.querySelectorAll('#training-steps p')];let i=0;const timer=setInterval(()=>{if(i>0)steps[i-1].innerHTML=steps[i-1].innerHTML.replace('●','✓').replace('○','✓');if(i<steps.length){steps[i].innerHTML=steps[i].innerHTML.replace('○','●');i++}else{clearInterval(timer);state.trained=true;document.getElementById('model-status').textContent='READY';document.getElementById('model-status').classList.add('ready-status');btn.textContent='Model created ✓';updatePanel()}},620)}
document.querySelectorAll('.lab-link').forEach(btn=>btn.addEventListener('click',()=>{state.lab=+btn.dataset.lab;document.querySelectorAll('.lab-link').forEach(x=>x.classList.toggle('active',x===btn));const l=labs[state.lab];document.getElementById('lab-eyebrow').textContent=l.eyebrow;document.querySelector('.lab-heading .eyebrow').textContent=l.eyebrow.replace(' OF 7','');document.querySelector('.lab-heading h1').innerHTML=l.title;document.querySelector('.lab-heading .intro').textContent=l.intro;if(state.lab===1){location.reload();return}document.querySelector('.lab-chip').innerHTML=`BUILD<br><strong>0${state.lab} / 07</strong>`;document.getElementById('lab-content').querySelector('.prediction-stage')?.remove();document.getElementById('lab-content').querySelector('.build-card')?.remove();let target=document.getElementById('dynamic-content');if(!target){target=document.createElement('div');target.id='dynamic-content';document.getElementById('lab-content').append(target)}target.innerHTML=content[state.lab];updatePanel();bindLab()}));
document.querySelectorAll('.prediction-option').forEach(b=>b.onclick=()=>{document.querySelectorAll('.prediction-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.getElementById('prediction-sentence').innerHTML=`A doctor works in a <strong>${b.dataset.word}.</strong> <span class="cursor">▍</span>`;document.getElementById('prediction-note').textContent='Context made this option most likely.'});document.getElementById('reset-prediction').onclick=()=>location.reload();document.getElementById('save-blueprint').onclick=()=>{state.name=document.getElementById('name-input').value||'My AI';state.purpose=document.getElementById('purpose-input').value||'A helpful AI';document.getElementById('save-blueprint').textContent='Blueprint saved ✓';updatePanel()};const modal=document.getElementById('modal-backdrop');document.getElementById('underhood').onclick=()=>modal.hidden=false;document.getElementById('truth-button').onclick=()=>modal.hidden=false;document.getElementById('modal-close').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};updatePanel();
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'set_ai_blueprint',title:'Set AI blueprint',description:'Update the visible working name and purpose for the prototype AI.',inputSchema:{type:'object',properties:{name:{type:'string'},purpose:{type:'string'}},required:['name','purpose'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input.name.trim()||!input.purpose.trim())throw new Error('A name and purpose are required.');state.name=input.name.trim();state.purpose=input.purpose.trim();updatePanel();return {name:state.name,purpose:state.purpose};}}).catch(()=>{});}
