/* Ideas lead; demonstrations and practice follow. Never reset existing learner work. */
const lessonChapters={
 lab1:{title:'Meet AI',idea:'AI is a family of computer systems that recognise patterns, make predictions or generate content. Many modern systems learn patterns from examples rather than relying only on rules someone writes.',why:'Recognising speech, identifying an object in a photo and generating an answer are different AI tasks. Your agent will use an existing AI’s language capability to help with a particular job.',limit:'A convincing answer can still be wrong. Learning about AI includes knowing when to check evidence—not just knowing how to ask a question.',demo:'A fixed alarm follows a time you set. A speech recogniser uses learned patterns to interpret a new voice. A text model uses learned patterns and the current request to generate an answer.',recap:'Explain what AI does, how a request guides its answer, and why a convincing answer can still be wrong.',next:'Discover the small text pieces that a language model processes.'},
 lab2:{title:'Inside AI’s Words',idea:'A text model processes small pieces called tokens. A token can be a whole word, part of a word, punctuation or another piece. Different models can divide the same text differently.',why:'The model represents these pieces as numbers. When generating text, it estimates which piece could come next using the pieces already present. Repeating that process builds an answer.',limit:'Tokens are not ideas the AI consciously thinks about. Our coloured pieces are illustrations, not the output of a real model tokenizer.',demo:'The word photosynthesis might be represented as one piece or several parts. A question mark can be a separate piece. The useful observation is that tokens are not always complete words.',recap:'Explain what tokens are, how a model generates text piece by piece, and why token boundaries can vary.',next:'See how examples guide the kind of answer your agent should give.'},
 lab3:{title:'Show Your Agent How',idea:'An example pairs a request with a useful response. It shows the agent what helpful work looks like: what to include, how to explain it and when to acknowledge a limit.',why:'Think of showing a new colleague a well-written reply. You are demonstrating a pattern to follow—not writing every reply they will ever need.',limit:'Three examples are a teaching starting point, not a guarantee of reliability. They do not teach the model every fact or replace reliable reference information.',demo:'A useful explanation demonstrates clarity. An answer admitting missing evidence demonstrates honesty. A short description of the agent’s job demonstrates focus.',recap:'Identify how examples guide useful responses, honest limits and focus, without replacing reliable reference information.',next:'Connect those examples to instructions and the temperature setting.'},
 lab4:{title:'Shape Its Behaviour',idea:'Instructions describe the agent’s job, boundaries and way of helping. Temperature changes how much variety the model allows when choosing its next text pieces. Temperature is not heat.',why:'Lower temperature tends to favour likely choices and produce more consistent responses. Higher temperature allows more varied choices. The right setting depends on the task, not on which number looks impressive.',limit:'Higher temperature does not make the model smarter. Lower temperature does not guarantee facts are correct. Tone and length also depend on instructions and the request.',demo:'For the same request, a lower setting may repeatedly choose similar wording. A higher setting may use different wording or approaches. Our two prepared replies illustrate possibilities, not a measured live experiment.',recap:'Explain how instructions guide behaviour and how temperature changes variety without guaranteeing accuracy.',next:'Bring the job, examples and instructions together as one agent setup.'},
 lab5:{title:'Assemble Your Agent',idea:'An agent is more than a reply generator: it combines an existing AI capability with a job, instructions, examples, information and available actions. Today you assemble the guidance; tomorrow you add a tool.',why:'The job gives direction. Instructions set boundaries. Examples illustrate useful answers. Reference information can supply facts. Each part serves a different purpose.',limit:'Saving a setup does not train a model, publish a service or prove the agent works. The course’s local setup demonstrates the parts; live generated agent replies need a connected model service.',demo:'Follow one request through the agent’s saved job, instruction and example. Notice why each part is relevant, rather than comparing a deliberately weak answer with a prepared good one.',recap:'Explain how your agent’s job, instructions and examples work together in one saved setup.',next:'Give your agent a relevant tool so it can take an action.'},
 lab6:{title:'Give It Tools',idea:'A tool is a function that performs a specific action and returns a result. The agent can use that result in its response instead of merely producing likely text.',why:'A useful tool follows from the job: a biology tutor can retrieve supplied notes, a business helper can calculate a profit, and a personal coach can save a next-step task.',limit:'Only enabled tools are available. Searching a saved note is not searching the internet; saving a task is not sending a reminder. Always inspect what actually happened.',demo:'The request establishes the need. The selected tool performs an action. Its result supplies evidence for the response. In this course the tool actions are real and local; the final response wording is illustrated.',recap:'Use a relevant tool, inspect its actual result and explain what it cannot do.',next:'Test the complete agent and reflect on your AI journey.'},
 lab7:{title:'Agent Launch Challenge',idea:'You have explored AI, tokens, examples, instructions, temperature, an agent setup and tools. Completion means connecting those ideas—not just reaching the last screen.',why:'A useful agent must be tested with an ordinary request, a request it cannot reliably answer and a tool task. Check whether it helps, admits limits and actually performs the claimed action.',limit:'A saved practice agent is not automatically a live online service. Local demonstrations and tool actions teach the structure; a connected model service is needed for real generated agent answers.',demo:'Trace a request: the job sets direction, instructions and examples guide the reply, the model supplies language capability, and a tool can return a real action result. Then check the response before relying on it.',recap:'Explain your agent’s job, connect its parts, and test its answers, limits and tool actions.',next:'Celebrate your completed learning journey and keep improving through careful testing.'}
};
const chapterChoices={
 ai:{options:['Yes. Any program that responds to input counts as AI.','No. A basic alarm can follow a fixed time without using AI.','Yes. Following programmed instructions means a program has learned from examples.'],correct:1,why:'Not every program uses AI. Following a fixed instruction is different from learning patterns from examples.'},
 source:{options:['The model automatically looks up every answer on the internet.','The saved examples contain every answer the model can ever give.','Learned patterns and the current context guide the generated response; tools may add information when available.'],correct:2,why:'Generation uses learned patterns and context. Internet access requires an available tool; examples are not an exhaustive answer list.'},
 evidence:{options:['Acknowledge that the required information is missing, rather than promise an exact outcome.','Give a likely outcome as a definite answer because it sounds realistic.','Repeat the request more clearly so the unknown outcome becomes certain.'],correct:0,why:'An unknown outcome needs evidence. Plausible wording and a clearer request cannot supply missing information.'},
 tokens:{options:['A token is always a word; punctuation is discarded.','A token can be a word, word part or punctuation, with boundaries depending on the model.','A token is a full sentence whose meaning the model has understood.'],correct:1,why:'Tokens are text pieces, not necessarily whole words or complete meanings.'}
};
function chapterPhase(){return project().guidance.chapters?.[store.page]||'learn';}
function setChapterPhase(phase){const p=project(),current=chapterPhase();const allowed=AI102Blocks.learningJourney.canTransition(current,phase,{demonstrationSeen:!!p.guidance.workedExamples?.[store.page],practiceFinished:!!p.guidance.practiceFinished?.[store.page],lessonCompleted:p.completed.includes(store.page)});if(!labDay(store.page)||!allowed)return;cancelVoice();p.guidance.chapters??={};p.guidance.chapters[store.page]=phase;if(phase==='practice'){p.guidance.practiceFinished??={};p.guidance.practiceFinished[store.page]=false;}save();render();evePageVisit='';eveTeachMoment(labDay(store.page),'Teach the current chapter phase only. Guide only the visible next action; do not introduce later stages.');}
function chapterMultipleChoices(){const input=document.querySelector('textarea[id^="day1-answer-"],#day2-answer');if(!input||input.closest('[hidden]'))return;const key=input.id==='day2-answer'?'tokens':input.id.replace('day1-answer-','');const q=chapterChoices[key];if(!q)return;const review=key==='tokens'?project().guidance.day2Answer:project().guidance.day1Answers?.[key];const question=key==='tokens'?'Which description of tokens is accurate?':day1Questions[key].question;input.form.hidden=true;input.hidden=true;const group=document.createElement('section');group.className='chapter-choices';group.setAttribute('aria-label','Practice question');group.innerHTML=`<h3>${esc(question)}</h3>${q.options.map((text,i)=>`<button class="choice ${review?.answer===text?'selected':''}" onclick="answerChapterChoice('${key}',${i})">${esc(text)}</button>`).join('')}<p role="status">${review?esc(review.feedback):'Choose the most accurate answer. Read all the options carefully.'}</p>`;input.form.before(group);}
function answerChapterChoice(key,index){const q=chapterChoices[key];if(!q||!q.options[index])return;const p=project(),answer=q.options[index],assessment=index===q.correct?'correct':'not_yet',review={answer,assessment,feedback:(assessment==='correct'?'Correct. ':'Not quite. ')+q.why};p.guidance.drafts??={};const page=key==='tokens'?'lab2':'lab1',id=key==='tokens'?'day2-answer':`day1-answer-${key}`;p.guidance.drafts[page]??={};p.guidance.drafts[page][id]=answer;if(key==='tokens')p.guidance.day2Answer=review;else{p.guidance.day1Answers??={};p.guidance.day1Answers[key]=review;}save();render();eveTeachMoment(labDay(page),`The learner selected an option. The page now shows this checked result: ${review.feedback} Explain only this result and the visible next action.`);}
function presentChapter(){const day=labDay(store.page),chapter=lessonChapters[store.page],main=document.querySelector('main');if(!day||!chapter||courseResuming||pendingCheck)return;const phase=chapterPhase();if(phase==='practice'){chapterMultipleChoices();const label=document.createElement('div');label.className='chapter-phase';label.innerHTML='<span>1. Learn</span><span>2. See</span><b>3. Practise</b><span>4. Recap</span><button class="button ghost" onclick="setChapterPhase(\'learn\')">Revisit the idea</button>';main.prepend(label);return;}const agent=day1Preset(project()).title;main.innerHTML=`<div class="chapter-phase"><b>${phase==='learn'?'1. Learn':phase==='see'?'2. See':'4. Recap'}</b><span>Learn → See → Practise → Recap</span></div>${header('MISSION '+day+' · YOUR AI JOURNEY',chapter.title,'With Eve and your '+agent)}<section class="card chapter-idea">${phase==='learn'?`<h2>The idea</h2><p class="chapter-main-idea">${esc(chapter.idea)}</p><h3>Why it matters</h3><p>${esc(chapter.why)}</p><div class="token-clue"><b>Keep this in mind</b><p>${esc(chapter.limit)}</p></div><button class="button" onclick="setChapterPhase('see')">See the idea in action →</button>`:phase==='see'?`<h2>See the idea in action</h2><p class="chapter-main-idea">${esc(chapter.demo)}</p><p><b>Your agent:</b> ${esc(agent)}</p><p><b>A relevant request:</b> ${esc((presetPractice[project().preset]||presetPractice.tutor).question)}</p><button class="button" onclick="setChapterPhase('practice')">Try the activity →</button><button class="button ghost" onclick="setChapterPhase('learn')">Back to the explanation</button>`:`<h2>What you learned</h2><p class="chapter-main-idea">${esc(chapter.recap)}</p><p>${esc(chapter.next)}</p><button class="button" onclick="continueChapter()">${day===7?'Complete AI 102 →':'Continue to Mission '+(day+1)+' →'}</button><button class="button ghost" onclick="setChapterPhase('practice')">Revisit the activity</button>`}</section>${eveVoiceButton(day)}${eveDebugMarkup()}`;voiceState(voiceSession.phase,eveDebug.error||'');}
function graduationPage(){const p=project(),missing=[1,2,3,4,5,6,7].filter(day=>!p.completed.includes(`lab${day}`));if(missing.length)return `${header('AI 102 · KEEP LEARNING','Your agent tests are complete.','Finish the remaining lessons before completing the course.')}<section class="card"><p>Lessons still to complete: ${missing.map(day=>'Mission '+day).join(', ')}.</p><button class="button" onclick="go('lab${missing[0]}')">Continue learning →</button></section>`;return `${header('AI 102 · MISSION ACCOMPLISHED','You understand the journey. You built an agent.','Congratulations, '+esc(p.guidance.learnerName)+'. This is a beginning you can build on.')}<section class="card chapter-idea"><h2>Meet ${esc(p.name||day1Preset(p).title)}</h2><p><b>Its job:</b> ${esc(p.purpose)}</p><p>You connected AI and tokens to examples, instructions, temperature and a useful tool. You reviewed an ordinary request, an uncertain request and a tool action.</p><div class="token-clue"><b>What you have today</b><p>A saved practice agent setup and local tool actions—not a published online agent. Live generated answers require a connected model service.</p></div><h3>Your next step</h3><p>Try new requests, check evidence and refine the guidance. Never treat a confident answer as proof.</p><div class="actions"><button class="button" onclick="exportProject()">Export my agent setup</button><button class="button secondary" onclick="go('dashboard')">View my agents</button><button class="button ghost" onclick="go('lab1')">Revisit the lessons</button></div></section>`;}
function continueChapter(){const day=labDay(store.page);const p=project();if(!day||!['recap','done'].includes(chapterPhase())||!p.completed.includes(store.page))return;p.guidance.chapters[store.page]='done';save();chapterOriginalGo(day===7?'graduation':`lab${day+1}`);}
let chapterOriginalGo;
function installCourseJourney(){
 day1Questions.evidence.question='Which response best handles the request below?';
 const baseRender=render;render=()=>{if(store.page==='graduation'){layout(graduationPage());return;}baseRender();presentChapter();};
 chapterOriginalGo=go;go=page=>{const day=labDay(store.page),p=project();if(day&&chapterPhase()==='practice'&&p.guidance.practiceFinished?.[store.page]&&page===(day===7?'dashboard':`lab${day+1}`)){cancelVoice();p.guidance.chapters??={};p.guidance.chapters[store.page]='recap';save();render();evePageVisit='';eveTeachMoment(day,'The current lesson is complete. Briefly recap it and invite the visible continuation button.');return;}chapterOriginalGo(page);};
 const context=teacherPageContext;teacherPageContext=day=>{const page=`lab${day}`,c=lessonChapters[page],phase=project().guidance.chapters?.[page]||'learn';if(store.page==='graduation')return 'Mission accomplished. Celebrate the learner’s journey honestly: saved practice setup, not a published live agent.';if(c&&store.page===page&&phase!=='practice')return `CURRENT PAGE: Mission ${day}. Chapter phase: ${phase}. Explain this idea as the main lesson, not as a subtitle: ${c.idea} Why it matters: ${c.why} Demonstration: ${c.demo} Limits: ${c.limit} Recap: ${c.recap} Teach the current phase only. Use the selected agent. Do not jump to questions or later lessons.`;return context(day);};
 const activity=eveActivityKey;eveActivityKey=day=>`${activity(day)}-${project().guidance.chapters?.[`lab${day}`]||'learn'}`;
 tinyChecks.lab1=['An answer is fluent and relevant. What gives you a stronger reason to rely on it?',['It matches the agent’s purpose and sounds confident','Its important claims agree with reliable evidence','A lower temperature produces the same wording twice'],1,'Relevance and consistency are useful, but reliable evidence is needed for important factual claims.'];
 tinyChecks.lab3=['Which example best guides a reliable answer?',['A confident answer that fills in any missing facts','A relevant response that explains clearly and admits missing evidence','A long response containing every topic the agent might encounter'],1,'A useful example combines relevance and clarity with honest limits. Length and confidence are not evidence.'];
 tinyChecks.lab4=['What does higher temperature mainly change?',['The amount of variety allowed in the model’s choices','The reliability of the facts in its examples','Whether the agent can access external tools'],0,'Temperature affects variety; evidence and tool availability are separate.'];
 tinyChecks.lab5=['Why assemble an agent setup?',['To change the underlying model’s learned facts','To connect the job, instructions and examples that guide its work','To prove the agent’s answers are accurate before testing'],1,'Assembly connects guidance. It neither trains the model nor proves reliability.'];
 tinyChecks.lab6=['Which statement about tools is accurate?',['A tool returns a specific action result that still needs inspection','Saving a task also schedules a notification by default','Searching a supplied note automatically checks the entire internet'],0,'Inspect the specific result. Saved tasks and notes do not imply external services.'];
 tinyChecks.lab7=['Which evidence best supports trusting an agent for a task?',['It sounds confident and has a finished-looking name','One good response to a question used in its examples','Tests on new requests, checked facts, honest limits and verified tool actions'],2,'Use varied tests and inspect evidence and actions. Completion is not a reliability guarantee.'];
}
