/* One lesson, four distinct purposes. Worked examples do not reveal practice answers. */
const lessonStageTitles={
 lab1:['AI is more than a chat window','Watch AI handle a request →','Apply what you know about AI'],
 lab2:['Text becomes pieces a model can process','Look inside a short sentence →','Investigate text pieces'],
 lab3:['Examples show what helpful work looks like','Follow a worked example →','Recognise what each example teaches'],
 lab4:['Instructions and temperature do different jobs','Compare possible word choices →','Choose a sensible starting setting'],
 lab5:['An agent needs connected parts','Follow a request through the setup →','Assemble your agent setup'],
 lab6:['Tools do jobs that text alone cannot do','Follow a tool action →','Run your agent’s suggested tool'],
 lab7:['Completion means knowing what you built','Inspect a worked test →','Test your complete agent']
};
function workedLessonExample(day){const p=project(),id=p.preset,t=day6ToolPlan(),sample=presetPractice[id]||presetPractice.tutor;
 if(day===1){const cases={tutor:['Why do we breathe faster after running?','Working muscles need more oxygen. Breathing faster helps bring in oxygen and remove carbon dioxide.'],business:['Write a polite message about a delayed delivery.','Hello. Your delivery has been delayed. I’m sorry for the inconvenience; I will send an update when I have a confirmed delivery time.'],coach:['I have twenty minutes but keep putting off my reading.','Start with one page for five minutes. Put your phone away, then decide whether to continue.']};const c=cases[id]||cases.tutor;return {title:'One request, one generated response',before:c[0],after:c[1],reason:'The request supplies context. A text model uses learned patterns to produce relevant wording. The response may be useful, but important factual claims still need checking.'};}
 if(day===2)return {title:'Inside “Hello, Eve!”',before:'Hello, Eve!',after:'[Hello] [,] [ Eve] [!]',reason:'This illustrated split includes words and punctuation. The model represents text pieces as numbers. A different model may use different boundaries; these brackets are not a live tokenizer result.'};
 if(day===3){const c={tutor:['Explain pollination in two short sentences.','Pollination happens when pollen reaches the part of a flower that receives it. It helps many plants reproduce.'],business:['Tell a customer we do not yet know their delivery date.','I do not have a confirmed delivery date yet. I will update you when it is confirmed.'],coach:['Help me plan a short walk without making promises about my health.','Pick a short route that suits your situation. If you have health concerns, ask a qualified professional for advice.']}[id]||['Give a short answer.','Start with the main point.'];return {title:'A request paired with a useful response',before:c[0],after:c[1],reason:'The pair demonstrates a response pattern, such as brevity or acknowledging a limit. For a new request, the agent should apply that pattern—not copy this answer regardless of the question.'};}
 if(day===4)return {title:'Variety is about choices, not intelligence',before:'The reply is about to continue: “Start with one ___”',after:'Lower-temperature illustration: step · step · step\nHigher-temperature illustration: step · action · task',reason:'The higher-setting illustration uses more varied choices for the same gap. It is not automatically longer, friendlier or more accurate. These are prepared possibilities, not measured model trials.'};
 if(day===5)return {title:'Trace a request through the agent',before:sample.question,after:`Job → ${p.purpose||day1Preset(p).purpose}\nInstructions → ${p.behavior}\nExamples → demonstrate useful response patterns\nExisting AI → supplies the language capability\nAvailable tools → perform supported actions`,reason:'These parts serve different roles. A request needs relevant guidance, not a new model or a new version for every lesson. In practice you will collect the current parts into one saved setup.'};
 if(day===6){const c={knowledge:['Find the pollination explanation in a supplied note.','Search saved note → “Pollination transfers pollen to the receptive part of a flower.”'],tasks:['Create task: Read one page tomorrow.','Task list action → a task is stored; no reminder has been scheduled.'],calculator:['What is 12 × 3?','Calculator action → 12 × 3 = 36.']}[t.id];return {title:`A worked ${t.name.toLowerCase()} action`,before:c[0],after:c[1],reason:'The request calls for a specific action. The tool returns information or a stored result, which the agent can use in a reply. This worked example is prepared; the next stage runs a different real local task.'};}
 return {title:'Review a failure before testing your agent',before:sample.hard,after:'Prepared flawed reply: “Yes. I know exactly what will happen. You can rely on my prediction.”',reason:'The reply claims certainty about missing or future information. A polished tone does not fix that failure. Your tests should check evidence, honest limits and actual tool results—not just how convincing the wording sounds.'};
}
function revealWorkedExample(){if(chapterPhase()!=='see')return;cancelVoice();const p=project();p.guidance.workedExamples??={};p.guidance.workedExamples[store.page]=true;save();render();eveTeachMoment(labDay(store.page),'Explain the revealed worked example only. Contrast what happened with what it does not prove. Do not give away practice answers.');}
function finishAssembledPractice(){if(store.page!=='lab5'||chapterPhase()!=='practice'||!project().model)return;complete('lab5');go('lab6');}
function day1PracticeMarkup(){const p=project(),x=presetPractice[p.preset]||presetPractice.tutor,step=p.guidance.day1Step||1;
 if(step===1&&!p.guidance.day1Predict)return `<h2>Distinguish AI from an ordinary program</h2>${day1AnswerBox('ai','Next: Make a prediction')}`;
 if(step===1)return `<h2>Make your own prediction</h2><p>Imagine your ${esc(day1Preset(p).title)} answering this new request:</p><blockquote class="prediction-request">${esc(x.question)}</blockquote><p>Write your prediction in your own words. You do not need to know the subject’s exact answer.</p>${day1AnswerBox('predict','See a sample answer')}`;
 if(step===2)return `<h2>Identify what guides a response</h2>${day1AnswerBox('source','What should I check?')}`;
 if(step===3)return `<h2>Spot the missing evidence</h2><blockquote class="prediction-request">${esc(x.hard)}</blockquote>${day1AnswerBox('evidence','Try a small task')}`;
 if(p.guidance.detailTask)return `<h2>Explain AI in your own words</h2><p>Use what you learned to give a short explanation—not a memorised definition.</p>${day1AnswerBox('explain','Check what I learned')}`;
 return `<h2>Decide what makes an answer trustworthy</h2><p>Your agent gives a clear answer to “${esc(x.question)}”. What should you do before relying on an important claim?</p><button class="button secondary" onclick="day1ChooseDetail(false)">Use it because it fits the agent’s job and sounds clear</button><button class="button secondary" onclick="day1ChooseDetail(true)">Check the important claim against reliable evidence</button><button class="button secondary" onclick="day1ChooseDetail(false)">Lower the temperature and trust the repeated wording</button><p id="detail-feedback" role="status"></p><button id="detail-next" class="button" hidden onclick="render()">Explain it in my own words →</button>`;
}
function day2PracticeMarkup(){const p=project(),q=p.samples[0]||(presetPractice[p.preset]||presetPractice.tutor).question,step=p.guidance.day2Step||1,seen=p.guidance.day2Discoveries||[];
 if(step===1)return `<h2>Predict a split, then inspect it</h2><p>Where might this request divide into text pieces? Predict silently before revealing the illustration.</p><blockquote class="prediction-request">${esc(q)}</blockquote><button class="button" onclick="startDay2Split()">Reveal the token pieces</button>`;
 if(step===2)return `<h2>Find three different kinds of piece</h2><div class="token-board">${day2TokenMarkup(q)}</div><div class="grid3">${[['word','Whole word'],['part','Word part'],['punctuation','Punctuation']].map(([key,label])=>`<button class="choice ${seen.includes(key)?'selected':''}" onclick="inspectDay2Token('${key}')">${label}</button>`).join('')}</div><div class="token-clue">${seen.length?`You inspected ${seen.length} of 3 piece types.`:'Select each type to inspect an example.'}</div><button class="button" ${seen.length===3?'':'disabled'} onclick="advanceDay2(3,'The learner inspected the three types. Invite changing the text in the experiment, without repeating the token definition.')">Experiment with the sentence →</button>`;
 if(step===3)return `<h2>Change the text and observe the difference</h2><p>Add punctuation, a number or a longer word. Compare the illustrated pieces before and after.</p><label for="token-text">Your sentence</label><textarea id="token-text" data-start="${esc(q)}" oninput="tokenize();updateDay2ExperimentButton()">${esc(p.guidance.drafts?.lab2?.['token-text']||q)}</textarea><div id="tokens" class="token-board"></div><p id="token-count"></p><button id="day2-experiment-next" class="button" disabled onclick="completeDay2Experiment()">Check what I learned →</button>`;
 return `<h2>Choose the accurate description</h2>${day2AnswerBox()}`;
}
function day3PracticeMarkup(){const p=project(),i=Math.min(p.guidance.day3ExampleStep||0,2),x=suggestedDay3Examples()[i],seen=p.guidance.day3Explored||[],review=p.guidance.day3Checks?.[i];return `<div class="eyebrow">EXAMPLE ${i+1} OF 3</div><h2>What response pattern does this pair show?</h2><blockquote class="prediction-request">${esc(x.input)}</blockquote><div class="answer">${esc(x.output)}</div><div class="chapter-choices">${['Giving relevant, useful help','Acknowledging missing evidence','Keeping the reply focused on the job'].map((label,j)=>`<button class="choice ${review?.selected===j?'selected':''}" onclick="checkDay3Pattern(${i},${j})">${label}</button>`).join('')}</div><p role="status">${review?esc(review.feedback):'Choose the strongest description of this example.'}</p><div class="actions"><button class="button secondary" ${i?'':'disabled'} onclick="moveDay3Example(-1)">Previous example</button><button class="button" ${seen.includes(i)&&review?.selected===i?'':'disabled'} onclick="${i<2?'moveDay3Example(1)':"finishLab('lab3','lab4')"}">${i<2?'Next example →':'Continue to behaviour →'}</button></div>`;}
function checkDay3Pattern(i,j){const p=project();if(![0,1,2].includes(i)||![0,1,2].includes(j))return;p.guidance.day3Checks??={};p.guidance.day3Checks[i]={selected:j,feedback:i===j?'Correct. '+suggestedDay3Examples()[i].why:'Not quite. Look at what this response mainly does, rather than its length or confident tone.'};save();if(i===j)exploreDay3Example(i);else render();}
function day4PracticeMarkup(){const p=project(),passed=p.guidance.day4PracticePassed;return `<h2>Choose a starting setting for your agent</h2><p>Your ${esc(day1Preset(p).title)} should answer similar requests consistently while following its preset instructions. Which choice is best justified?</p><div class="chapter-choices"><button class="choice" onclick="chooseTemperaturePractice(true)">Start lower for consistency, and still check important facts</button><button class="choice" onclick="chooseTemperaturePractice(false)">Start higher because varied wording makes factual claims more reliable</button><button class="choice" onclick="chooseTemperaturePractice(false)">Start lower so reference information is no longer needed</button></div><p role="status">${esc(p.guidance.day4PracticeFeedback||'Choose a setting and the reason for it.')}</p><button class="button" ${passed?'':'disabled'} onclick="finishTemperaturePractice()">Continue with this setting →</button>`;}
function chooseTemperaturePractice(correct){const p=project();p.guidance.day4PracticePassed=correct;p.guidance.day4PracticeFeedback=correct?'Correct. Consistency is a useful starting goal, not a guarantee of accuracy.':'Not quite. Separate variety from accuracy and the need for evidence.';save();render();}
function finishTemperaturePractice(){const p=project();if(!p.guidance.day4PracticePassed)return;p.behavior=day1Preset(p).behavior;p.temperature=.2;const x=presetPractice[p.preset]||presetPractice.tutor;p.evaluation=[x.question,x.hard];complete('lab4');save();go('lab5');}
function day5PracticeMarkup(){const p=project(),ready=p.examples.length>=3,c=p.model?.configuration||p;return `<h2>${p.model?'Your setup is assembled':'Collect your agent’s current parts'}</h2><div class="mini"><div><span>Job</span><b>${esc(c.purpose||day1Preset(p).purpose)}</b></div><div><span>Instructions</span><b>${esc(c.behavior)}</b></div><div><span>Examples</span><b>${c.examples?.length||0}</b></div><div><span>Starting temperature</span><b>${c.temperature??p.temperature}</b></div></div>${p.model?'<p>Your setup is saved in this browser. You will add its tool next.</p><button class="button" onclick="finishAssembledPractice()">Continue to tools →</button>':`<p>${ready?'Check that these parts match your selected agent, then assemble them.':'Finish the three suggested-example tasks in Mission 3 first.'}</p><button class="button" ${ready?'':'disabled'} onclick="createModel()">Assemble my agent →</button>`}`;}
function day6PracticeMarkup(){const p=project(),t=day6ToolPlan(),r=p.guidance.day6Result;return `<h2>Carry out this task with ${t.name}</h2><blockquote class="prediction-request">${esc(t.request)}</blockquote><p>${t.id==='knowledge'?'Use the supplied course note—not an internet search.':t.id==='tasks'?'Save a task locally—not a scheduled reminder.':'Compute the difference—not a guessed number.'}</p><div class="actions"><button class="button secondary" onclick="enableDay6Tool()">${p.tools[t.id]?'✓ Tool enabled':'Use this tool'}</button><button class="button" ${p.tools[t.id]?'':'disabled'} onclick="tryDay6Tool()">Run this task →</button></div>${r?`<div class="token-clue"><b>Action performed</b><p>${esc(r.action)}</p><b>Actual result</b><p>${esc(r.result)}</p></div><p>Inspect whether the result matches the requested task.</p>`:''}<p id="day6-error" role="alert"></p><button class="button" ${r?'':'disabled'} onclick="finishLab('lab6','lab7')">I inspected the result · Continue →</button>`;}
const testCriteria={normal:['Its important claims answer the request and can be checked','Professional wording alone proves the facts','Repeating an example guarantees it works on a new question'],difficult:['Fill the gap with a confident plausible prediction','Identify missing information instead of guaranteeing an unknown outcome','Use lower temperature to make the missing information certain'],tool:['Judge only the wording of the final sentence','Assume that an enabled tool must have been used','Inspect the actual action and result against the request']};
function checkFinalTestCriterion(i){if(!launchTrial)return;const kind=launchTrial.kind,correct={normal:0,difficult:1,tool:2}[kind];if(i!==correct){document.getElementById('test-criterion-feedback').textContent='Not quite. Focus on evidence and the actual result, not wording or assumptions.';return;}reviewLaunchTrial();}
function day7PracticeMarkup(){const container=document.createElement('div');container.innerHTML=guidedLaunch();return Array.from(container.children).filter(el=>el.classList.contains('card')).map(el=>el.outerHTML).join('');}
function redesignedPractice(day){return day===1?day1PracticeMarkup():day===2?day2PracticeMarkup():day===3?day3PracticeMarkup():day===4?day4PracticeMarkup():day===5?day5PracticeMarkup():day===6?day6PracticeMarkup():day7PracticeMarkup();}
function renderLessonStage(){const day=labDay(store.page),c=lessonChapters[store.page],main=document.querySelector('main');if(!day||!c||courseResuming||pendingCheck)return;const phase=chapterPhase(),titles=lessonStageTitles[store.page],demo=workedLessonExample(day),shown=project().guidance.workedExamples?.[store.page];
 if(phase==='practice'){main.innerHTML=`<div class="chapter-phase"><b>Step 3 of 4 · Practice</b></div>${header('MISSION '+day+' · PRACTICE',titles[2],'Apply what you learned with your '+day1Preset(project()).title)}${day===7?redesignedPractice(day):`<section class="card">${redesignedPractice(day)}</section>`}${eveDebugMarkup()}`;if(day===7)main.querySelectorAll('.classroom-hero')[1]?.remove();chapterMultipleChoices();setTimeout(()=>{tokenize();updateDay2ExperimentButton?.();},0);voiceState(voiceSession.phase,eveDebug.error||'');return;}
 const body=phase==='learn'?`<h2>${titles[0]}</h2><p class="chapter-main-idea">${esc(c.idea)}</p><h3>Why this matters for your agent</h3><p>${esc(c.why)}</p><div class="token-clue"><b>An important limit</b><p>${esc(c.limit)}</p></div><button class="button" onclick="setChapterPhase('see')">${titles[1]}</button>`:phase==='see'?`<h2>${esc(demo.title)}</h2><p><b>${day===4?'Before the next word is chosen':'The request'}</b></p><blockquote class="prediction-request">${esc(demo.before)}</blockquote>${shown?`<div class="answer">${esc(demo.after)}</div><h3>What happened—and why</h3><p>${esc(demo.reason)}</p>`:''}${shown?'':'<button class="button secondary" onclick="revealWorkedExample()">Show what happens</button>'}<div class="actions"><button class="button" ${shown?'':'disabled'} onclick="setChapterPhase('practice')">Try it yourself →</button></div>`:`<h2>Mission ${day} complete</h2><p><b>You can now:</b> ${esc(c.recap)}</p><p><b>Your next step:</b> ${esc(c.next)}</p><div class="actions"><button class="button" onclick="continueChapter()">${day===7?'Complete AI 102 →':'Continue to Mission '+(day+1)+' →'}</button><button class="button ghost" onclick="setChapterPhase('practice')">Review your practice</button></div>`;
 main.innerHTML=`<div class="chapter-phase"><b>${phase==='learn'?'Step 1 of 4 · Lesson':phase==='see'?'Step 2 of 4 · Worked example':'Step 4 of 4 · Lesson complete'}</b></div>${header('MISSION '+day+' · AI 102',c.title,'Your '+day1Preset(project()).title+' journey')}<section class="card chapter-idea">${body}</section>${eveDebugMarkup()}`;voiceState(voiceSession.phase,eveDebug.error||'');
}
function installLessonDesign(){presentChapter=renderLessonStage;const context=teacherPageContext;teacherPageContext=day=>{if(store.page!==`lab${day}`||pendingCheck)return context(day);const c=lessonChapters[store.page],phase=chapterPhase(),demo=workedLessonExample(day);if(phase==='learn')return `CURRENT PAGE: Mission ${day}. Current stage: Lesson. Teach ${c.idea} Relevance: ${c.why} Limit: ${c.limit} Do not introduce the worked example, recap or practice questions yet.`;if(phase==='see')return `CURRENT PAGE: Mission ${day}. Current stage: Worked example. Request: ${demo.before}. ${project().guidance.workedExamples?.[store.page]?`Displayed result: ${demo.after}. Explain: ${demo.reason}`:'The result is not revealed yet. Invite Show what happens; do not reveal the result first.'} This case differs from practice. Never call it a live AI reply.`;if(phase==='practice')return `CURRENT PAGE: Mission ${day}. Current stage: Practice. Visible task: ${document.querySelector('main .card')?.innerText.slice(0,1800)||''}. Respond to the learner’s exact question. Do not repeat the lesson definition or worked example. Give a targeted hint if needed, not an answer before an attempt. Invite only the visible action. Open predictions and personal explanations are in the learner’s own words.`;return `CURRENT PAGE: Mission ${day}. Current stage: Lesson complete. Summarise briefly: ${c.recap} Next: ${c.next}`;};const trial=runLaunchTrial;runLaunchTrial=async kind=>{await trial(kind);const output=document.getElementById('trial-answer');if(!output||!launchTrial)return;output.querySelector('button')?.remove();output.insertAdjacentHTML('beforeend',`<h3>Which check is appropriate for this result?</h3><div class="chapter-choices">${testCriteria[kind].map((label,i)=>`<button class="choice" onclick="checkFinalTestCriterion(${i})">${label}</button>`).join('')}</div><p id="test-criterion-feedback" role="status"></p>`);};}
