/* Streamed speech with button-only interruption and queued teaching events. */
window.EveRealtime=(()=>{
 let pc=null,dc=null,audio=null,connecting=null,epoch=0,revision=0,day=0,spokenDay=0,context=null,responseActive=false,audioSpeaking=false,awaiting=false,events=[],lastActivity=0,watch,callId=null,closing=Promise.resolve(),sessionScope='',responseWelcome=false,welcomeTranscriptReady=false,welcomeAudioCompleted=false;
 const enabled=()=>window.BUILD_AI_CONFIG?.realtimeEnabled===true;
 let pendingGuide=null;
 const intentKey='ai102-eve-active-project';
 function remember(active){try{if(active)sessionStorage.setItem(intentKey,store.active);else sessionStorage.removeItem(intentKey);}catch{}}
 const loadingAnimation=()=>'<div class="eve-loading-animation" aria-hidden="true"><img src="assets/eve-teacher.png" alt=""><div class="eve-loading-dots"><i></i><i></i><i></i></div></div>';
 const busy=()=>responseActive||audioSpeaking||awaiting;
 function microphone(){}
 function drain(){microphone();if(!busy()&&pendingGuide){const next=pendingGuide;pendingGuide=null;void guide(...next);}}
 const send=event=>{if(dc?.readyState==='open')dc.send(JSON.stringify(event));};
 async function api(path,body){const r=await fetch((BUILD_AI_CONFIG.apiBaseUrl||'')+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok){if(r.status===409&&!/already connected/i.test(data.detail||''))CourseSession.block(data.detail,true);throw Error(data.detail||'Eve could not connect.');}return data;}
 function paint(){if(!enabled()||typeof voiceSession==='undefined')return;const host=document.getElementById('eve-live-host');if(!host)return;const state=voiceSession.phase==='error'?'error':pc&&dc?.readyState!=='open'?'connecting':awaiting&&!pc?'connecting':audioSpeaking?'speaking':responseActive||awaiting?'preparing':pc?'ready':connecting?'connecting':'idle';let controls=document.getElementById('eve-live-controls');if(!controls){controls=document.createElement('div');controls.id='eve-live-controls';controls.className='eve-live-controls';host.append(controls);}controls.replaceChildren();const loading=['connecting','preparing'].includes(state);controls.setAttribute('aria-busy',String(loading));if(loading)controls.insertAdjacentHTML('beforeend',loadingAnimation());const status=document.createElement('span');status.setAttribute('role','status');const labels={speaking:'Eve is guiding this step',preparing:'Eve is preparing the next idea',connecting:'Getting Eve ready',ready:'Eve will guide the next step automatically',idle:'Eve will begin with the lesson',error:'Eve could not continue'};status.textContent=labels[state]+'. '+(state==='error'?'Use Try again below.':loading?'She’ll continue automatically.':'');controls.dataset.eveState=state;controls.append(status);}
 function interrupt(){if(responseActive)send({type:'response.cancel'});send({type:'output_audio_buffer.clear'});responseActive=false;audioSpeaking=false;awaiting=false;events=[];paint();}
 function stop(notify=true,preserveIntent=false){const keep=preserveIntent&&voiceSession.enabled;remember(keep);const id=callId;callId=null;pendingGuide=null;epoch++;revision++;clearInterval(watch);watch=null;events=[];awaiting=false;responseActive=false;audioSpeaking=false;connecting=null;sessionScope='';responseWelcome=false;welcomeTranscriptReady=false;welcomeAudioCompleted=false;pc?.close();dc?.close();if(audio){audio.pause();audio.srcObject=null;audio.remove();}pc=dc=audio=null;if(typeof voiceSession!=='undefined'){voiceSession.generation++;voiceSession.enabled=keep;voiceSession.phase='idle';}paint();if(id&&notify&&enabled()&&CourseSession.active)closing=api('/v1/teacher/realtime/stop',{call_id:id}).catch(()=>{});}
 function finishWelcomeIfComplete(){if(responseWelcome&&welcomeTranscriptReady&&welcomeAudioCompleted){project().guidance.eveGreeted=true;save();responseWelcome=false;welcomeTranscriptReady=false;welcomeAudioCompleted=false;}}
 async function onEvent(event,token){
  if(token!==epoch)return;lastActivity=Date.now();
  if(event.type==='response.created'){responseActive=true;spokenDay=day;awaiting=false;welcomeTranscriptReady=false;updateEveDebug('Eve is preparing her reply.');paint();}
  if(event.type==='output_audio_buffer.started'){responseActive=true;audioSpeaking=true;updateEveDebug('Eve audio playback started.');paint();}
  if(event.type==='response.output_audio_transcript.done'||event.type==='response.audio_transcript.done'){if(event.transcript){saveEveTurn(spokenDay,'eve',event.transcript);welcomeTranscriptReady=responseWelcome;updateEveDebug('Live Eve replied.',{reply:event.transcript,error:''});finishWelcomeIfComplete();}paint();}
  if(event.type==='output_audio_buffer.stopped'||event.type==='output_audio_buffer.cleared'){const completed=event.type==='output_audio_buffer.stopped';responseActive=false;audioSpeaking=false;awaiting=false;voiceSession.phase='idle';if(completed){welcomeAudioCompleted=responseWelcome;finishWelcomeIfComplete();}else{responseWelcome=false;welcomeTranscriptReady=false;welcomeAudioCompleted=false;}updateEveDebug(completed?'Eve finished audio playback.':'Eve audio was interrupted.');paint();}
  if(event.type==='error'){if(['response_cancel_not_active','output_audio_buffer_clear_empty'].includes(event.error?.code))return;const message='Eve’s live connection was interrupted. Please try again.';stop();voiceState('error',message);paint();}
  microphone();if(event.type==='output_audio_buffer.stopped')drain();
 }
 async function connect(payload){
  if(pc&&dc?.readyState==='open')return;if(connecting)return connecting;
  const token=epoch;connecting=(async()=>{
   await closing;if(token!==epoch)return;if(!await CourseSession.check())throw Error('Continue on this device before talking to Eve.');
   // If a stop request was dropped, the same verified lease recovers its call.
   if(!await CourseSession.start())throw Error('Eve could not recover her connection. Please try again.');if(token!==epoch)return;
   pc=new RTCPeerConnection();audio=document.createElement('audio');audio.autoplay=true;audio.setAttribute('playsinline','');audio.hidden=true;document.body.append(audio);pc.ontrack=e=>{audio.srcObject=e.streams[0];void audio.play().catch(()=>{voiceState('error','Your browser blocked Eve’s sound. Use Try again below.');});};pc.addTransceiver('audio',{direction:'recvonly'});dc=pc.createDataChannel('oai-events');dc.onmessage=e=>{try{void onEvent(JSON.parse(e.data),token);}catch{}};
   pc.onconnectionstatechange=()=>{if(token===epoch&&['failed','disconnected'].includes(pc?.connectionState)){stop();voiceState('error','Eve lost her connection. Your work is saved. Try again.');paint();}};
   const offer=await pc.createOffer();await pc.setLocalDescription(offer);const result=await api('/v1/teacher/realtime',{sdp:offer.sdp,context:payload});if(token!==epoch){void api('/v1/teacher/realtime/stop',{call_id:result.call_id}).catch(()=>{});return;}callId=result.call_id;
   context=result;await pc.setRemoteDescription({type:'answer',sdp:result.sdp});await new Promise((resolve,reject)=>{if(dc.readyState==='open')return resolve();const timer=setTimeout(()=>reject(Error('Eve took too long to connect. Try again.')),15000);dc.onopen=()=>{clearTimeout(timer);resolve();};dc.onerror=()=>{clearTimeout(timer);reject(Error('Eve could not open live audio.'));};});
   if(token!==epoch)return;voiceSession.phase='listening';voiceSession.enabled=true;lastActivity=Date.now();const started=Date.now();watch=setInterval(()=>{if(!busy()&&(Date.now()-lastActivity>90000||Date.now()-started>900000)){stop(true,true);paint();}},5000);paint();
  })().catch(error=>{if(token===epoch){stop();voiceState('error',error.name==='NotAllowedError'?'Allow microphone access to talk to Eve, or continue reading.':error.message);paint();}throw error;}).finally(()=>{if(token===epoch)connecting=null;});return connecting;
 }
 async function guide(d,message,transition=null,exact=false){
  if(!enabled()||!voiceSession.enabled||!CourseSession.active)return;remember(true);claimEveTeachingEvent(d);if(busy()){pendingGuide=[d,message,transition,exact];return;}const scope=`mission-${d}`;if(pc&&sessionScope&&sessionScope!==scope)stop(true,true);day=d;const rev=++revision,payload=evePayload(d,message,'guidance',transition);if(exact){payload.feedback_mode='checked_feedback';payload.current_question='';payload.choice_mode='none';payload.activity='CURRENT STATE: The learner has already submitted an answer and the site has checked it. Speak the supplied checked feedback only, then stop.';}awaiting=true;voiceSession.phase='thinking';microphone();paint();
  try{await connect(payload);if(rev!==revision||!pc)return;sessionScope=scope;context=await api('/v1/teacher/realtime/context',payload);if(rev!==revision||!pc)return;send({type:'session.update',session:{type:'realtime',instructions:context.instructions}});
   // A new activity has fresh, private teaching context; it is never learner speech.
   const questionRule=payload.welcome_mode==='mission_briefing'?'This is the one first Mission Briefing welcome. Follow WELCOME MODE exactly, end by directing the learner to choose their starting mission, and do not add a question.':payload.feedback_mode==='checked_feedback'?'The learner already answered and the site already checked it. Speak only the supplied checked feedback exactly, without repeating the question, asking for an answer, or adding another question. Stop after the feedback.':payload.answer_state?'The visible written answer has already been checked. Do not ask for it again. Acknowledge its saved result and guide only the visible next action.':payload.current_question?'Ask only the visible question and tell the learner to type in the writing box. Never ask for a spoken answer.':payload.choice_mode==='before_choice'?'A multiple-choice activity is unanswered. Do not state, quote, paraphrase, compare, eliminate, hint at or explain any option or the correct answer. Give only a neutral direction to select the strongest answer on the page.':payload.choice_mode==='after_choice'?'The learner has now selected an option. Explain only the result shown on the page. If it is wrong, explain the misconception without naming the correct option.':'Do not ask any question and do not request an answer because no writing box is visible.';
    responseWelcome=payload.welcome_mode==='mission_briefing';welcomeTranscriptReady=false;welcomeAudioCompleted=false;send({type:'response.create',response:{instructions:context.instructions+'\nFor this turn only: '+(exact?'Speak this checked feedback exactly: ':'Guide this current event in your own words, not by reading instructions: ')+message+'\nFinal interaction rule: '+questionRule,output_modalities:['audio']}});microphone();paint();
  }catch(error){if(rev===revision){stop();voiceState('error',error.message);paint();}}
 }
 async function startForPage(){voiceSession.enabled=true;remember(true);day=store.page==='intro'?0:labDay(store.page)||0;await guide(day,'Continue the current activity naturally. If I have already been welcomed, do not greet again.');}
 function install(){if(!enabled())return;try{if(project().guidance.learnerName&&sessionStorage.getItem(intentKey)===store.active){courseResuming=false;voiceSession.enabled=true;}}catch{}const state=voiceState;voiceState=(phase,error='')=>{state(phase,error);paint();};const cancel=cancelVoice;cancelVoice=()=>{cancel();};stopEve=()=>stop();useEve=()=>startForPage();retryEve=()=>startForPage();toggleEveRecording=()=>startForPage();eveTeachMoment=(d,message,transition)=>guide(d,message,transition);playLiveEve=(text,d)=>guide(d,text,null,true);sendLiveEve=async(d,text)=>{day=d;await connect(evePayload(d,text));send({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text}]}});send({type:'response.create'});};
  const navigate=go;go=page=>{navigate(page);};const renderPage=render;render=()=>{renderPage();paint();};window.addEventListener('pagehide',()=>stop(true,true));
 }
 return {install,guide,stop,interrupt,paint,startForPage,get connected(){return !!pc;}};
})();
